<div class="m-box_related">
  <div class="l-contents">
    <div class="m-box_related_inner">
      <div class="l-contents-thin">
        <h2 class="m-box_related_hdg"><i class="icon-chain_01"></i>関連リンク</h2>
        <div class="m-box_related_list m-box_related_list-sub">
          <ul>
            <li>
              <a href="/event/">
                <div><i class="icon-news-event_01"></i></div>
                <p>イベント</p>
              </a>
            </li>
          </ul>
        </div>
      </div>
    </div>
  </div>
</div>