<div class="m-box_related">
  <div class="l-contents">
    <div class="m-box_related_inner">
      <div class="l-contents-thin">
        <h2 class="m-box_related_hdg"><i class="icon-chain_01"></i>関連リンク</h2>
        <div class="m-box_related_list m-box_related_list-main">
          <ul>
            <li>
              <a href="/sp/foreign/" target="_blank">
                <figure><img src="/assets/images/links/bnr_relation_foreign.jpg" alt=""></figure>
                <p>外国語学部　学部ウェブサイト</p>
              </a>
            </li>
            <li>
              <a href="/academics/syllabus/find/">
                <figure><img src="/assets/images/links/bnr_relation_syllabus.jpg" alt=""></figure>
                <p>シラバス</p>
              </a>
            </li>
          </ul>
        </div>
        <div class="m-box_related_list m-box_related_list-sub">
          <ul>
            <li>
              <a href="/campus/tuition/scholarship01.html">
                <div><i class="icon-academics_01"></i></div>
                <p>名城大学内奨学金</p>
              </a>
            </li>
          </ul>
        </div>
      </div>
    </div>
  </div>
</div>