<div class="m-box_related">
  <div class="l-contents">
    <div class="m-box_related_inner">
      <div class="l-contents-thin">
        <h2 class="m-box_related_hdg"><i class="icon-chain_01"></i>関連リンク</h2>
        <div class="m-box_related_list m-box_related_list-main">
          <ul>
            <li>
              <a href="https://ls.lawlibrary.jp/LS/LoginForm.aspx?P=249G" target="_blank">
                <figure><img src="/assets/images/links/bnr_relation_lawlibrary.jpg" alt=""></figure>
                <p>教育支援システム</p>
              </a>
            </li>
            <li>
              <a href="https://www.d1-law.com/" target="_blank">
                <figure><img src="/assets/images/links/bnr_relation_d1-law.jpg" alt=""></figure>
                <p>判例体系・文献情報</p>
              </a>
            </li>
            <li>
              <a href="https://www.lli-hanrei.com/" target="_blank">
                <figure><img src="/assets/images/links/bnr_relation_lli-hanrei.jpg" alt=""></figure>
                <p>LLI 主要法律雑誌</p>
              </a>
            </li>
          </ul>
        </div>
        <div class="m-box_related_list m-box_related_list-sub">
          <ul>
            <li>
              <a href="/career/results/academics/law_school.html">
                <div><i class="icon-career_01"></i></div>
                <p>法務研究科　就職・進路実績</p>
              </a>
            </li>
            <li>
              <a href="/campus/tuition/scholarship01.html">
                <div><i class="icon-academics_01"></i></div>
                <p>名城大学内奨学金</p>
              </a>
            </li>
          </ul>
        </div>
      </div>
    </div>
  </div>
</div>