<div class="m-box_related">
  <div class="l-contents">
    <div class="m-box_related_inner">
      <div class="l-contents-thin">
        <h2 class="m-box_related_hdg"><i class="icon-chain_01"></i>関連リンク</h2>
        <div class="m-box_related_list m-box_related_list-main">
          <ul>
            <li>
              <a href="http://www-yaku.meijo-u.ac.jp" target="_blank">
                <figure><img src="/assets/images/links/bnr_relation_pharmacy.jpg" alt=""></figure>
                <p>薬学部　学部ウェブサイト</p>
              </a>
            </li>
            <li>
              <a href="http://yyipe.meijo-u.ac.jp" target="_blank">
                <figure><img src="/assets/images/links/bnr_relation_yyipe.jpg" alt=""></figure>
                <p>多職種連携教育</p>
              </a>
            </li>
            <li>
              <a href="http://www-yaku.meijo-u.ac.jp/kenkyu/index.html" target="_blank">
                <figure><img src="/assets/images/links/bnr_relation_yaku-kenkyu.jpg" alt=""></figure>
                <p>研究室紹介</p>
              </a>
            </li>
            <li>
              <a href="https://gkmsyllabus.meijo-u.ac.jp/camweb/slbssrch.do">
                <figure><img src="/assets/images/links/bnr_relation_syllabus.jpg" alt=""></figure>
                <p>シラバス</p>
              </a>
            </li>
          </ul>
        </div>
        <div class="m-box_related_list m-box_related_list-sub">
          <ul>
            <li>
              <a href="/career/results/academics/pharmacy.html">
                <div><i class="icon-career_01"></i></div>
                <p>薬学部　就職・進路状況</p>
              </a>
            </li>
            <li>
              <a href="/campus/tuition/scholarship01.html">
                <div><i class="icon-academics_01"></i></div>
                <p>名城大学内奨学金</p>
              </a>
            </li>
          </ul>
        </div>
      </div>
    </div>
  </div>
</div>