<div class="m-box_related">
  <div class="l-contents">
    <div class="m-box_related_inner">
      <div class="l-contents-thin">
        <h2 class="m-box_related_hdg"><i class="icon-chain_01"></i>関連リンク</h2>
        <div class="m-box_related_list m-box_related_list-main">
          <ul>
            <li>
              <a href="http://meijoy.meijo-u.ac.jp/" target="_blank">
                <figure><img src="/assets/images/links/bnr_relation_meic2.jpg" alt=""></figure>
                <p>MeiC2</p>
              </a>
            </li>
          </ul>
        </div>
      </div>
    </div>
  </div>
</div>