<!-- InstanceBeginEditable name="footerInclude" -->
		<!-- 各ページ：フッター部分 -->
		<footer class="l-footer">
<div class="l-footer_copy">
<small>&copy; 2018 Meijo University</small>
</div>
</footer>		<!-- InstanceEndEditable -->
		
	</div>
	
	<script src="/assets/js/libraries.js"></script>
<script src="/assets/js/common.js"></script>
<script src="/assets/js/english.js"></script>
<script language="JavaScript" type="text/javascript" src="//o.advg.jp/ojs?aid=6570&pid=1" charset="UTF-8"></script>
<noscript><iframe src="//o.advg.jp/oif?aid=6570&pid=1" width="1" height="1"></iframe></noscript>
<script src="/assets/js/ss_suggest_config.js"></script>