<header class="l-header">
<h1 class="l-header_logo"><a href="/english/"><i class="icon-meijo-symbolmark_01"></i><img src="/assets/images/logo-meijo01.svg" alt="MEIJO UNIVERSITY"></a></h1>
<nav class="l-header_gnav">
<ul class="l-header_gnav_list">
<li class="l-header_gnav_list_item l-header_gnav_list_item-about">
<p><a href="/english/about/"><i class="icon-arrow-right_01"></i>About</a></p>
</li>
<li class="l-header_gnav_list_item l-header_gnav_list_item-academics">
<p><a href="/english/academics/"><i class="icon-arrow-right_01"></i>Faculties/Graduate Schools</a></p>
</li>
<li class="l-header_gnav_list_item l-header_gnav_list_item-research">
<p><a href="/english/research/"><i class="icon-arrow-right_01"></i>Academic Research</a></p>
</li>
<li class="l-header_gnav_list_item l-header_gnav_list_item-student_life">
<p><a href="/english/student_life/"><i class="icon-arrow-right_01"></i>Student Life</a></p>
</li>
<li class="l-header_gnav_list_item l-header_gnav_list_item-admissions">
<p><a href="/english/admissions/"><i class="icon-arrow-right_01"></i>Admissions</a></p>
</li>
<li class="l-header_gnav_list_item l-header_gnav_list_item-library">
<p><a href="/english/library/"><i class="icon-arrow-right_01"></i>Libraries</a></p>
</li>
</ul>
<ul class="l-header_gnav_other">
<li><a href="/">JAPANESE</a></li>
<li><a href="/english/">ENGLISH</a></li>
</ul>
</nav>
<p class="l-header_toggle"><button type="button" class="js-action-headertoggle"><i></i></button></p>
<nav class="l-header_snav">
<ul class="l-header_snav_list">
<li class="l-header_snav_list_item l-header_snav_list_item-access"><a href="/english/about/campusmap.html"><i class="icon-access_01"></i><span>ACCESS</span></a></li>
<li class="l-header_snav_list_item l-header_snav_list_item-search"><a href="javascript:void(0);" class="js-action-headermodal" data-headermodal="search"><i class="icon-search_01"></i><span>SEARCH</span></a></li>
</ul>
</nav>
<nav class="l-header_language">
<ul>
<li><a href="/"><span>JP</span></a></li>
<li><span class="is-active"><span>EN</span></span></li>
</ul>
</nav>
<nav class="l-header_modal" data-headermodal="search">
<div class="l-header_modal_inner">
<h2 class="l-header_modal_hdg"><i class="icon-search_01"></i><span>SEARCH</span></h2>
<div class="l-header_modal_search">
<form action="/english/search/index.html" id="cse-search-box">
<input type="hidden" name="cx" value="002002868988497249087:s7bb5bexmyi">
<input type="hidden" name="cof" value="FORID:10">
<input type="hidden" name="ie" value="UTF-8">
<input type="text" id="keywords" name="q">
<button type="submit"><i class="icon-search_01"></i></button>
</form>
</div>
<button class="l-header_modal_close js-action-headermodal-close"><i class="icon-close_01"></i></button>
</div>
<div class="l-header_modal_bg js-action-headermodal-close"></div>
</nav>
</header>