<div class="m-box_feature">
  <h2 class="m-hdg_lv2-headline">FEATURE</h2>
  <div class="m-box_feature_slider js-action-feature">
    <ul class="m-box_feature_slider_list clearfix js-action-feature-slider">
      <li><a href="#"><img src="/assets/images/pic-feature01.png" alt=""></a></li>
      <li><a href="#"><img src="/assets/images/pic-feature02.png" alt=""></a></li>
      <li><a href="#"><img src="/assets/images/pic-feature03.png" alt=""></a></li>
      <li><a href="#"><img src="/assets/images/pic-feature01.png" alt=""></a></li>
      <li><a href="#"><img src="/assets/images/pic-feature02.png" alt=""></a></li>
      <li><a href="#"><img src="/assets/images/pic-feature03.png" alt=""></a></li>
    </ul>
    <div class="m-box_feature_slider_controll js-action-feature-controll">
      <a class="prev"></a>
      <a class="next"></a>
    </div>
  </div>
</div>