<div class="m-box_feature">
  <h2 class="m-hdg_lv2-headline">FEATURE</h2>
  <div class="m-box_feature_slider js-action-feature">
    <ul class="m-box_feature_slider_list clearfix js-action-feature-slider">
    
    	
    	
    <li><a href="/campus/freshmen/" target="_blank"><img src="https://www.meijo-u.ac.jp/banner/assets/%E6%96%B0%E5%B9%B4%E5%BA%A6%E3%81%8A%E5%BD%B9%E7%AB%8B%E3%81%A1%E6%83%85%E5%A0%B1.png" alt="新年度お役立ち情報"></a></li>
  		
    	
  	
    	
    	
    <li><a href="/challengers/" target="_blank"><img src="https://www.meijo-u.ac.jp/banner/assets/challengers_bnr.jpg" alt="名城大学チャレンジ支援プログラム"></a></li>
  		
    	
  	
    	
    	
    <li><a href="/about/fund/fund01/" target="_blank"><img src="https://www.meijo-u.ac.jp/banner/assets/banner_0328.jpg" alt="名城サポーターズ募金"></a></li>
  		
    	
  	
    	
    	
    <li><a href="/mag/hello-world/" target="_blank"><img src="https://www.meijo-u.ac.jp/banner/assets/pic-feature07.jpg" alt="HELLO WORLD!"></a></li>
  		
    	
  	
    	
    	
    <li><a href="/nagoyadome/"><img src="https://www.meijo-u.ac.jp/banner/assets/pic-feature04.png" alt="ナゴヤドーム前キャンパス"></a></li>
  		
    	
  	
    	
    	
    <li><a href="http://plat.meijo-u.ac.jp/" target="_blank"><img src="https://www.meijo-u.ac.jp/banner/assets/pic-feature01.png" alt="社会連携センターPLAT"></a></li>
  		
    	
  	
    	
    	
    <li><a href="/about/ms26/manabi/"><img src="https://www.meijo-u.ac.jp/banner/assets/pic-feature03.png" alt="MS-26 学びのコミュニティ"></a></li>
  		
    	
  	
    </ul>
    <div class="m-box_feature_slider_controll js-action-feature-controll">
      <a class="prev"></a>
      <a class="next"></a>
    </div>
  </div>
</div>