<div class="m-box_related">
  <div class="l-contents">
    <div class="m-box_related_inner">
      <div class="l-contents-thin">
        <h2 class="m-box_related_hdg"><i class="icon-chain_01"></i>関連リンク</h2>
        <div class="m-box_related_list m-box_related_list-sub">
          <ul>
            <li>
              <a href="#" target="_blank">
                <div><i class="icon-pen_01"></i></div>
                <p>icon-pen_01</p>
              </a>
            </li>
            <li>
              <a href="#">
                <div><i class="icon-person_01"></i></div>
                <p>icon-person_01</p>
              </a>
            </li>
            <li>
              <a href="#">
                <div><i class="icon-device_01"></i></div>
                <p>icon-device_01</p>
              </a>
            </li>
            <li>
              <a href="#">
                <div><i class="icon-library_01"></i></div>
                <p>icon-library_01</p>
              </a>
            </li>
            <li>
              <a href="#">
                <div><i class="icon-career_01"></i></div>
                <p>icon-career_01</p>
              </a>
            </li>
            <li>
              <a href="#">
                <div><i class="icon-news-event_01"></i></div>
                <p>icon-news-event_01</p>
              </a>
            </li>
            <li>
              <a href="#">
                <div><i class="icon-admissions_01"></i></div>
                <p>icon-admissions_01</p>
              </a>
            </li>
            <li>
              <a href="#">
                <div><i class="icon-academics_01"></i></div>
                <p>icon-academics_01</p>
              </a>
            </li>
            <li>
              <a href="#">
                <div><i class="icon-campuslife_01"></i></div>
                <p>icon-campuslife_01</p>
              </a>
            </li>
            <li>
              <a href="#">
                <div><i class="icon-about_01"></i></div>
                <p>icon-about_01</p>
              </a>
            </li>
            <li>
              <a href="#">
                <div><i class="icon-photo_01"></i></div>
                <p>icon-photo_01</p>
              </a>
            </li>
            <li>
              <a href="#">
                <div><i class="icon-meijo-symbolmark_01"></i></div>
                <p>icon-meijo-symbolmark_01</p>
              </a>
            </li>
            <li>
              <a href="#">
                <div><i class="icon-search_01"></i></div>
                <p>icon-search_01</p>
              </a>
            </li>
            <li>
              <a href="#">
                <div><i class="icon-access_01"></i></div>
                <p>icon-access_01</p>
              </a>
            </li>
          </ul>
        </div>
      </div>
    </div>
  </div>
</div>

<div class="m-box_feature">
  <h2 class="m-hdg_lv2-headline">FEATURE</h2>
  <div class="m-box_feature_slider js-action-feature">
    <ul class="m-box_feature_slider_list clearfix js-action-feature-slider">
      <li><a href="#"><img src="/assets/images/pic-feature01.png" alt=""></a></li>
      <li><a href="#"><img src="/assets/images/pic-feature02.png" alt=""></a></li>
      <li><a href="#"><img src="/assets/images/pic-feature03.png" alt=""></a></li>
      <li><a href="#"><img src="/assets/images/pic-feature01.png" alt=""></a></li>
      <li><a href="#"><img src="/assets/images/pic-feature02.png" alt=""></a></li>
      <li><a href="#"><img src="/assets/images/pic-feature03.png" alt=""></a></li>
    </ul>
    <div class="m-box_feature_slider_controll js-action-feature-controll">
      <a class="prev"></a>
      <a class="next"></a>
    </div>
  </div>
</div>