<footer class="l-footer">
  <div class="l-footer_inner clearfix">
    <h1 class="l-footer_logo">
      <a href="/">
        <i class="icon-meijo-symbolmark_01"></i>
        <img src="/assets/images/logo-meijo01.svg" alt="MEIJO UNIVERSITY">
      </a>
    </h1>
    <nav class="l-footer_snav">
      <p class="l-footer_snav_siryo">
        <a href="https://www.meijo-u.ac.jp/admissions/pamphlet/request.html" target="_blank">資料請求 
          <i class="icon-link_01"></i>
        </a>
      </p>
      <div class="l-footer_snav_sns clearfix">
        <ul>
          <li>
            <a href="https://www.facebook.com/meijo.university" target="_blank" class="facebook">
              <i class="icon-facebook_01"></i>
            </a>
          </li>
          <li>
            <a href="https://twitter.com/meijo_univ" target="_blank" class="twitter">
              <i class="icon-twitter_01"></i>
            </a>
          </li>
          <li>
            <a href="https://page.line.me/meijonavi" target="_blank" class="line">
              <i class="icon-line_01"></i>
            </a>
          </li>
          <li>
            <a href="https://www.instagram.com/meijo_navi/" target="_blank" class="instagram">
              <i class="icon-instagram_01"></i>
            </a>
          </li>
        </ul>
      </div>
    </nav>
    <nav class="l-footer_gnav clearfix">
      <div class="l-footer_gnav_main clearfix">
        <ul>
          <li>
            <a href="/about/public.html">情報公開</a>
          </li>
          <li>
            <a href="/employ/">採用情報</a>
          </li>
          <li>
            <a href="/link/">リンク集</a>
          </li>
          <li>
            <a href="/contact/">お問い合わせ</a>
          </li>
        </ul>
      </div>
      <div class="l-footer_gnav_icon">
        <ul>
          <li>
            <a href="/about/fund/">
              <i class="icon-shien_01"></i>ご支援をお考えの方
            </a>
          </li>
          <li>
            <a href="/library/">
              <i class="icon-library_01"></i>附属図書館
            </a>
          </li>
        </ul>
      </div>
      <div class="l-footer_gnav_sub">
        <ul>
          <li>
            <a href="https://rpportal.meijo-u.ac.jp/Portal/" target="_blank">統合ポータルサイト 
              <i class="icon-link_01"></i>
            </a>
          </li>
          <li>
            <a href="/sitemap/">サイトマップ</a>
          </li>
          <li>
            <a href="/policy/">ポリシー</a>
          </li>
        </ul>
      </div>
    </nav>
  </div>
  <div class="l-footer_copy">
    <small>&copy; 2018 Meijo University</small>
  </div>
</footer>
<script src="/assets/js/libraries.js"></script>
<script src="/assets/js/common.js?v=<?php echo filemtime($_SERVER['DOCUMENT_ROOT'] . '/assets/js/common.js'); ?>"></script>
<script language="JavaScript" type="text/javascript" src="//o.advg.jp/ojs?aid=6570&pid=1" charset="UTF-8"></script>
<noscript>
  <iframe src="//o.advg.jp/oif?aid=6570&pid=1" width="1" height="1"></iframe>
</noscript>
<script src="/assets/js/ss_suggest_config.js"></script>