<div class="cms-tag">
<div class="l-contents">
	<div class="l-contents-thin">
	<!-- InstanceBeginEditable name="コンテンツ編集領域" -->
	
		<h2 class="m-hdg_lv2"><a href="/about/campus/tenpaku.html" target="_blank">天白キャンパス</a></h2>
		
		<h3 class="m-hdg_lv3">公務員全体ガイダンス</h3>
		<div class="m-box_table m-box_table-col2">
			<div class="m-box_table_inner">
				<div class="m-box_table_item">
					<h4 class="m-hdg_lv4">日程</h4>
					どちらかへ出席（同じ内容です）<br />第1回　4月12日（木）13:10～14:40<br />第2回　4月13日（金）17:00～18:30
				</div>
				<div class="m-box_table_item">
					<h4 class="m-hdg_lv4">教室</h4>
					共通講義棟南　1階<br />S101講義室
				</div>
			</div>
		</div>
		
		<h3 class="m-hdg_lv3">申込方法等の総合ガイダンス</h3>
		<div class="m-box_table m-box_table-col2">
			<div class="m-box_table_inner">
				<div class="m-box_table_item">
					<h4 class="m-hdg_lv4">日程</h4>
					どちらかへ出席（同じ内容です）<br />第1回　4月9日（月）17:00～18:00<br />第2回　4月10日（火）17:00～18:00
				</div>
				<div class="m-box_table_item">
					<h4 class="m-hdg_lv4">教室</h4>
					共通講義棟北　1階<br />N101講義室（名城ホール）
				</div>
			</div>
		</div>
		

		<h2 class="m-hdg_lv2"><a href="/about/campus/dome.html" target="_blank">ナゴヤドーム前キャンパス</a></h2>
		
		<h3 class="m-hdg_lv3">講座別ガイダンス</h3>
		<div class="m-box_table m-box_table-col2">
			<div class="m-box_table_inner">
				<div class="m-box_table_item">
					<h4 class="m-hdg_lv4">日程</h4>
					日程は講座ページ参照<br />4月16日（月）～4月21日（土）
				</div>
				<div class="m-box_table_item">
					<h4 class="m-hdg_lv4">教室</h4>
					講座ごとに異なりますので講座ページまたは、掲示で確認してください。
				</div>
			</div>
		</div>
				

		<div class="m-list_common">
			<ul>
				<li><a href="/career/qualification/index.html" target="_blank">公務員・資格取得支援(エクステンション)</a></li>
			</ul>
		</div>
<!-- InstanceEndEditable -->
	</div>
</div>
</div>
