<header class="l-header">
<h1 class="l-header_logo"><a href="/"><i class="icon-meijo-symbolmark_01"></i><img src="/assets/images/logo-meijo01.svg" alt="MEIJO UNIVERSITY"></a></h1>
<nav class="l-header_gnav">
<ul class="l-header_gnav_list">
<li class="l-header_gnav_list_item l-header_gnav_list_item-news">
<p><a href="/news/"><i class="icon-arrow-right_01"></i>ニュース</a></p>
</li>
<li class="l-header_gnav_list_item l-header_gnav_list_item-admissions">
<p><a href="/admissions/"><i class="icon-arrow-right_01"></i>入試情報</a></p>
</li>
<li class="l-header_gnav_list_item l-header_gnav_list_item-academics js-action-accordion" data-device="sp">
<p><a href="/academics/" class="js-action-accordion-title"><i class="icon-plus_01"></i>学部・大学院</a></p>
<ul class="js-action-accordion-body">
<li>
<p><a href="/academics/"><i class="icon-arrow-right_01"></i>学部・大学院トップ</a></p>
</li>
<li class="js-action-accordion">
<p><a href="javascript:void(0);" class="js-action-accordion-title"><i class="icon-plus_01"></i>法学部</a></p>
<ul class="js-action-accordion-body">
<li>
<p><a href="/academics/law/"><i class="icon-arrow-right_01"></i>法学部トップ</a></p>
</li>
<li>
<p><a href="/academics/law/"><i class="icon-arrow-right_01"></i>法学科</a></p>
</li>
</ul>
</li>
<li class="js-action-accordion">
<p><a href="javascript:void(0);" class="js-action-accordion-title"><i class="icon-plus_01"></i>経営学部</a></p>
<ul class="js-action-accordion-body">
<li>
<p><a href="/academics/business/"><i class="icon-arrow-right_01"></i>経営学部トップ</a></p>
</li>
<li>
<p><a href="/academics/business/business/"><i class="icon-arrow-right_01"></i>経営学科</a></p>
</li>
<li>
<p><a href="/academics/business/international/"><i class="icon-arrow-right_01"></i>国際経営学科</a></p>
</li>
</ul>
</li>
<li class="js-action-accordion">
<p><a href="javascript:void(0);" class="js-action-accordion-title"><i class="icon-plus_01"></i>経済学部</a></p>
<ul class="js-action-accordion-body">
<li>
<p><a href="/academics/economics/"><i class="icon-arrow-right_01"></i>経済学部トップ</a></p>
</li>
<li>
<p><a href="/academics/economics/economics/"><i class="icon-arrow-right_01"></i>経済学科</a></p>
</li>
<li>
<p><a href="/academics/economics/industrial/"><i class="icon-arrow-right_01"></i>産業社会学科</a></p>
</li>
</ul>
</li>
<li class="js-action-accordion">
<p><a href="javascript:void(0);" class="js-action-accordion-title"><i class="icon-plus_01"></i>外国語学部</a></p>
<ul class="js-action-accordion-body">
<li>
<p><a href="/academics/foreign/"><i class="icon-arrow-right_01"></i>外国語学部トップ</a></p>
</li>
<li>
<p><a href="/academics/foreign/international/"><i class="icon-arrow-right_01"></i>国際英語学科</a></p>
</li>
</ul>
</li>
<li class="js-action-accordion">
<p><a href="javascript:void(0);" class="js-action-accordion-title"><i class="icon-plus_01"></i>人間学部</a></p>
<ul class="js-action-accordion-body">
<li>
<p><a href="/academics/human/"><i class="icon-arrow-right_01"></i>人間学部トップ</a></p>
</li>
<li>
<p><a href="/academics/human/human/"><i class="icon-arrow-right_01"></i>人間学科</a></p>
</li>
</ul>
</li>
<li class="js-action-accordion">
<p><a href="javascript:void(0);" class="js-action-accordion-title"><i class="icon-plus_01"></i>都市情報学部</a></p>
<ul class="js-action-accordion-body">
<li>
<p><a href="/academics/urban/"><i class="icon-arrow-right_01"></i>都市情報学部トップ</a></p>
</li>
<li>
<p><a href="/academics/urban/urban/"><i class="icon-arrow-right_01"></i>都市情報学科</a></p>
</li>
</ul>
</li>
<li class="js-action-accordion">
<p><a href="javascript:void(0);" class="js-action-accordion-title"><i class="icon-plus_01"></i>理工学部</a></p>
<ul class="js-action-accordion-body">
<li>
<p><a href="/academics/sci_tech/"><i class="icon-arrow-right_01"></i>理工学部トップ</a></p>
</li>
<li>
<p><a href="/academics/sci_tech/mathematics/"><i class="icon-arrow-right_01"></i>数学科</a></p>
</li>
<li>
<p><a href="/academics/sci_tech/information/"><i class="icon-arrow-right_01"></i>情報工学科</a></p>
</li>
<li>
<p><a href="/academics/sci_tech/electrical/"><i class="icon-arrow-right_01"></i>電気電子工学科</a></p>
</li>
<li>
<p><a href="/academics/sci_tech/materials/"><i class="icon-arrow-right_01"></i>材料機能工学科</a></p>
</li>
<li>
<p><a href="/academics/sci_tech/chemistry/"><i class="icon-arrow-right_01"></i>応用化学科</a></p>
</li>
<li>
<p><a href="/academics/sci_tech/mechanical/"><i class="icon-arrow-right_01"></i>機械工学科</a></p>
</li>
<li>
<p><a href="/academics/sci_tech/vehicle/"><i class="icon-arrow-right_01"></i>交通機械工学科</a></p>
</li>
<li>
<p><a href="/academics/sci_tech/mechatronics/"><i class="icon-arrow-right_01"></i>メカトロニクス工学科</a></p>
</li>
<li>
<p><a href="/academics/sci_tech/civil/"><i class="icon-arrow-right_01"></i>社会基盤デザイン工学科</a></p>
</li>
<li>
<p><a href="/academics/sci_tech/environmental/"><i class="icon-arrow-right_01"></i>環境創造学科</a></p>
</li>
<li>
<p><a href="/academics/sci_tech/architecture/"><i class="icon-arrow-right_01"></i>建築学科</a></p>
</li>
</ul>
</li>
<li class="js-action-accordion">
<p><a href="javascript:void(0);" class="js-action-accordion-title"><i class="icon-plus_01"></i>農学部</a></p>
<ul class="js-action-accordion-body">
<li>
<p><a href="/academics/agriculture/"><i class="icon-arrow-right_01"></i>農学部トップ</a></p>
</li>
<li>
<p><a href="/academics/agriculture/agrobiol_res/"><i class="icon-arrow-right_01"></i>生物資源学科</a></p>
</li>
<li>
<p><a href="/academics/agriculture/appl_biol_chem/"><i class="icon-arrow-right_01"></i>応用生物化学科</a></p>
</li>
<li>
<p><a href="/academics/agriculture/environ_biosci/"><i class="icon-arrow-right_01"></i>生物環境科学科</a></p>
</li>
</ul>
</li>
<li class="js-action-accordion">
<p><a href="javascript:void(0);" class="js-action-accordion-title"><i class="icon-plus_01"></i>薬学部</a></p>
<ul class="js-action-accordion-body">
<li>
<p><a href="/academics/pharmacy/"><i class="icon-arrow-right_01"></i>薬学部トップ</a></p>
</li>
<li>
<p><a href="/academics/pharmacy/pharmacy/"><i class="icon-arrow-right_01"></i>薬学科</a></p>
</li>
</ul>
</li>
<li>
<p><a href="/academics/g_law/"><i class="icon-arrow-right_01"></i>法学研究科</a></p>
</li>
<li>
<p><a href="/academics/g_economics/"><i class="icon-arrow-right_01"></i>経営学研究科</a></p>
</li>
<li>
<p><a href="/academics/g_economics/"><i class="icon-arrow-right_01"></i>経済学研究科</a></p>
</li>
<li>
<p><a href="/academics/g_human/"><i class="icon-arrow-right_01"></i>人間学研究科</a></p>
</li>
<li>
<p><a href="/academics/g_urban/"><i class="icon-arrow-right_01"></i>都市情報学研究科</a></p>
</li>
<li>
<p><a href="/academics/g_sci_tech/"><i class="icon-arrow-right_01"></i>理工学研究科</a></p>
</li>
<li>
<p><a href="/academics/g_agriculture/"><i class="icon-arrow-right_01"></i>農学研究科</a></p>
</li>
<li>
<p><a href="/academics/g_pharmacy/"><i class="icon-arrow-right_01"></i>薬学研究科</a></p>
</li>
<li>
<p><a href="/academics/g_env_human/"><i class="icon-arrow-right_01"></i>総合学術研究科</a></p>
</li>
<li>
<p><a href="/academics/law_school/"><i class="icon-arrow-right_01"></i>法務研究科(法科大学院)</a></p>
</li>
<li>
<p><a href="/academics/thesis/"><i class="icon-arrow-right_01"></i>博士学位論文</a></p>
</li>
<li>
<p><a href="/academics/tc/"><i class="icon-arrow-right_01"></i>教職課程・学芸員課程</a></p>
</li>
<li>
<p><a href="/academics/education/"><i class="icon-arrow-right_01"></i>教育への取り組み</a></p>
</li>
</ul>
</li>
<li class="l-header_gnav_list_item l-header_gnav_list_item-campus js-action-accordion" data-device="sp">
<p><a href="/campus/" class="js-action-accordion-title"><i class="icon-plus_01"></i>学生生活</a></p>
<ul class="js-action-accordion-body">
<li>
<p><a href="/campus/"><i class="icon-arrow-right_01"></i>学生生活トップ</a></p>
</li>
<li>
<p><a href="/campus/tuition/"><i class="icon-arrow-right_01"></i>学費・奨励金</a></p>
</li>
<li>
<p><a href="/campus/activities/"><i class="icon-arrow-right_01"></i>課外活動（クラブ、ボランティア）</a></p>
</li>
<li>
<p><a href="/campus/freshmen.html"><i class="icon-arrow-right_01"></i>新入生スタートアップガイド</a></p>
</li>
<li>
<p><a href="/campus/register.html"><i class="icon-arrow-right_01"></i>在学生の皆さま</a></p>
</li>
<li>
<p><a href="/campus/info/"><i class="icon-arrow-right_01"></i>学修ガイド</a></p>
</li>
<li>
<p><a href="/campus/application/"><i class="icon-arrow-right_01"></i>各種申請・施設利用</a></p>
</li>
<li>
<p><a href="/campus/life/"><i class="icon-arrow-right_01"></i>生活情報・健康管理</a></p>
</li>
</ul>
</li>
<li class="l-header_gnav_list_item l-header_gnav_list_item-career js-action-accordion" data-device="sp">
<p><a href="/career/" class="js-action-accordion-title"><i class="icon-plus_01"></i>就職・資格</a></p>
<ul class="js-action-accordion-body">
<li>
<p><a href="/career/"><i class="icon-arrow-right_01"></i>就職・資格トップ</a></p>
</li>
<li>
<p><a href="/career/results/"><i class="icon-arrow-right_01"></i>就職・進路実績</a></p>
</li>
<li>
<p><a href="/career/m_career.html"><i class="icon-arrow-right_01"></i>キャリアセンターの支援プログラム</a></p>
</li>
<li>
<p><a href="/career/internship.html"><i class="icon-arrow-right_01"></i>インターンシップ支援</a></p>
</li>
<li>
<p><a href="/career/mcap.html"><i class="icon-arrow-right_01"></i>M-CAP（エアライン就職支援）</a></p>
</li>
<li>
<p><a href="/career/international_st.html"><i class="icon-arrow-right_01"></i>留学生就職促進プログラム</a></p>
</li>
<li>
<p><a href="/career/qualification/"><i class="icon-arrow-right_01"></i>公務員・資格取得支援</a></p>
</li>
<li>
<p><a href="/career/license.html"><i class="icon-arrow-right_01"></i>教員免許・学芸員免許の取得支援</a></p>
</li>
<li>
<p><a href="/career/center.html"><i class="icon-arrow-right_01"></i>キャリアセンターのご案内</a></p>
</li>
<li>
<p><a href="/career/link.html"><i class="icon-arrow-right_01"></i>就職に役立つリンク集</a></p>
</li>
<li>
<p><a href="/career/qa.html"><i class="icon-arrow-right_01"></i>よくある質問</a></p>
</li>
<li>
<p><a href="/career/appointed.html"><i class="icon-arrow-right_01"></i>就職内定者の皆さまへ</a></p>
</li>
<li>
<p><a href="/career/alumni.html"><i class="icon-arrow-right_01"></i>卒業生の皆さまへ</a></p>
</li>
<li>
<p><a href="/career/company/"><i class="icon-arrow-right_01"></i>企業の皆さまへ</a></p>
</li>
<li>
<p><a href="/career/student/"><i class="icon-arrow-right_01"></i>在学生専用ページ</a></p>
</li>
</ul>
</li>
<li class="l-header_gnav_list_item l-header_gnav_list_item-about js-action-accordion" data-device="sp">
<p><a href="/about/" class="js-action-accordion-title"><i class="icon-plus_01"></i>大学概要</a></p>
<ul class="js-action-accordion-body">
<li>
<p><a href="/about/"><i class="icon-arrow-right_01"></i>大学概要トップ</a></p>
</li>
<li>
<p><a href="/about/message.html"><i class="icon-arrow-right_01"></i>理事長挨拶・学長挨拶</a></p>
</li>
<li>
<p><a href="/about/outline/"><i class="icon-arrow-right_01"></i>大学基本情報</a></p>
</li>
<li>
<p><a href="/about/ms26/"><i class="icon-arrow-right_01"></i>学校法人名城大学の基本戦略 MS-26</a></p>
</li>
<li>
<p><a href="/about/data/"><i class="icon-arrow-right_01"></i>数字で見る名城大学</a></p>
</li>
<li>
<p><a href="/about/pr.html"><i class="icon-arrow-right_01"></i>パンフレット・広報</a></p>
</li>
<li>
<p><a href="/about/campus/"><i class="icon-arrow-right_01"></i>アクセス・キャンパス紹介</a></p>
</li>
<li>
<p><a href="/about/action/"><i class="icon-arrow-right_01"></i>本学の取り組み</a></p>
</li>
<li>
<p><a href="/about/application/"><i class="icon-arrow-right_01"></i>取引および各種申請</a></p>
</li>
<li>
<p><a href="/about/fund/"><i class="icon-arrow-right_01"></i>名城大学への募金・寄附</a></p>
</li>
<li>
<p><a href="/about/public.html"><i class="icon-arrow-right_01"></i>情報公開</a></p>
</li>
</ul>
</li>
<li class="l-header_gnav_list_item l-header_gnav_list_item-more js-action-accordion" data-device="sp">
<p><a href="javascript:void(0);" class="js-action-accordion-title js-action-headermodal" data-headermodal="more"><i class="icon-plus_01"></i><i class="icon-plus_01 b-is-hidden-sp"></i>MORE</a></p>
<ul class="js-action-accordion-body">
<li>
<p><a href="/international/"><i class="icon-arrow-right_01"></i>国際交流</a></p>
</li>
<li>
<p><a href="/research/"><i class="icon-arrow-right_01"></i>研究・産学官連携</a></p>
</li>
<li>
<p><a href="/social/"><i class="icon-arrow-right_01"></i>社会貢献・公開講座</a></p>
</li>
</ul>
</li>
</ul>
<ul class="l-header_gnav_special">
<li><a href="#"><i class="icon-arrow-right_01"></i><span class="b-ff-en-meijomag b-fw-bold">MEIJO MAG</span></a></li>
<li><a href="/sp/meijoresearch/"><i class="icon-arrow-right_01"></i><span class="b-ff-en-serif">MEIJO RESEARCH</span></a></li>
</ul>
<ul class="l-header_gnav_contact">
<li><a href="https://www.meijo-u.ac.jp/admissions/pamphlet/request.html" target="_blank">資料請求 <i class="icon-link_01"></i></a></li>
<li><a href="https://f.msgs.jp/webapp/form/19002_wccb_1/index.do" target="_blank">取材・お問い合わせ</a></li>
</ul>
<ul class="l-header_gnav_other">
<li><a href="/english/">ENGLISH</a></li>
<li><a href="https://rpportal.meijo-u.ac.jp/Portal/" target="_blank">総合ポータルサイト <i class="icon-link_01"></i></a></li>
</ul>
</nav>
<p class="l-header_toggle"><button type="button" class="js-action-headertoggle"><i></i></button></p>
<nav class="l-header_snav">
<ul class="l-header_snav_list">
<li class="l-header_snav_list_item l-header_snav_list_item-access"><a href="javascript:void(0);" class="js-action-headermodal" data-headermodal="access"><i class="icon-access_01"></i><span>ACCESS</span></a></li>
<li class="l-header_snav_list_item l-header_snav_list_item-search"><a href="javascript:void(0);" class="js-action-headermodal" data-headermodal="search"><i class="icon-search_01"></i><span>SEARCH</span></a></li>
</ul>
</nav>
<nav class="l-header_language">
<ul>
<li><span class="is-active"><span>JP</span></span></li>
<li><a href="/english/"><span>EN</span></a></li>
</ul>
</nav>
<nav class="l-header_modal" data-headermodal="more">
<div class="l-header_modal_inner">
<h2 class="l-header_modal_hdg"><i class="icon-plus_01"></i><span>MORE</span></h2>
<ul class="l-header_modal_list l-header_modal_list-more">
<li><a href="/international/"><i class="icon-arrow-right_01"></i>国際交流</a></li>
<li><a href="/research/"><i class="icon-arrow-right_01"></i>研究・産学官連携</a></li>
<li><a href="/social/"><i class="icon-arrow-right_01"></i>社会貢献・公開講座</a></li>
<li class="b-is-hidden-sp"><a href="#" class="m-btn m-btn-s"><i class="icon-arrow-right_01"></i><span class="b-ff-en-meijomag">MEIJO MAG</span></a></li>
<li class="b-is-hidden-sp"><a href="/sp/meijoresearch/" class="m-btn m-btn-s"><i class="icon-arrow-right_01"></i><span class="b-ff-en-serif">MEIJO RESEARCH</span></a></li>
</ul>
</div>
<button class="l-header_modal_close js-action-headermodal-close"><i class="icon-close_01"></i></button>
<div class="l-header_modal_bg js-action-headermodal-close"></div>
</nav>
<nav class="l-header_modal" data-headermodal="access">
<div class="l-header_modal_inner">
<h2 class="l-header_modal_hdg"><i class="icon-access_01"></i><span>ACCESS</span></h2>
<ul class="l-header_modal_list l-header_modal_list-access">
<li><a href="/about/campus/tenpaku.html"><i class="icon-arrow-right_01"></i>天白キャンパス</a></li>
<li><a href="/about/campus/yagoto.html"><i class="icon-arrow-right_01"></i>八事キャンパス</a></li>
<li><a href="/about/campus/dome.html"><i class="icon-arrow-right_01"></i>ナゴヤドーム前キャンパス</a></li>
<li><a href="/about/campus/farm.html"><i class="icon-arrow-right_01"></i>春日井（鷹来）キャンパス附属農場</a></li>
<li><a href="/about/campus/nisshin.html"><i class="icon-arrow-right_01"></i>日進キャンパス（総合グラウンド）</a></li>
</ul>
</div>
<button class="l-header_modal_close js-action-headermodal-close"><i class="icon-close_01"></i></button>
<div class="l-header_modal_bg js-action-headermodal-close"></div>
</nav>
<nav class="l-header_modal" data-headermodal="search">
<div class="l-header_modal_inner">
<h2 class="l-header_modal_hdg"><i class="icon-search_01"></i><span>SEARCH</span></h2>
<div class="l-header_modal_search">
<form action="/search/" id="ss-form1" method="get">
<input type="text" id="ss-query1" name="query" autocomplete="off" aria-autocomplete="off">
<button type="submit"><i class="icon-search_01"></i></button>
</form>
</div>
<button class="l-header_modal_close js-action-headermodal-close"><i class="icon-close_01"></i></button>
</div>
<div class="l-header_modal_bg js-action-headermodal-close"></div>
</nav>
</header>