<div class="p-top_banner">
          <div class="l-contents p-top_banner_inner">
            <div class="l-contents-thin p-top_banner_inner_inner">
              <div class="p-top_banner_slider js-action-bannerslider">
                <ul class="p-top_banner_slider_list clearfix js-action-bannerslider-slider">
                
    			
    			
    			<li><a href="http://wuke.jp/meijo-teacher/" target="_blank"><img src="https://www.meijo-u.ac.jp/banner/assets/bnr_footer_15.png" alt="名城大学教員免許状更新講習"></a></li>
  				
    			
  				
    			
    			
    			<li><a href="/admissions/"><img src="https://www.meijo-u.ac.jp/banner/assets/bnr_footer_03.png" alt="受験生応援サイト Meijo Navi"></a></li>
  				
    			
  				
    			
    			
    			<li><a href="/about/ms26/manabi/"><img src="https://www.meijo-u.ac.jp/banner/assets/bnr_footer_05.png" alt="MS-26 学びのコミュニティ"></a></li>
  				
    			
  				
    			
    			
    			<li><a href="/social/contribution/"><img src="https://www.meijo-u.ac.jp/banner/assets/bnr_footer_11.png" alt="公開講座"></a></li>
  				
    			
  				
    			
    			
    			<li><a href="/about/action/no_smoking/"><img src="https://www.meijo-u.ac.jp/banner/assets/bnr_footer_09.png" alt="学内全面禁煙"></a></li>
  				
    			
  				
    			
    			
    			<li><a href="/sp/led/"><img src="https://www.meijo-u.ac.jp/banner/assets/bnr_footer_01.png" alt="光デバイス研究"></a></li>
  				
    			
  				
    			
    			
    			<li><a href="/sp/nano/"><img src="https://www.meijo-u.ac.jp/banner/assets/bnr_footer_02.png" alt="ナノマテリアル研究"></a></li>
  				
    			
  				
    			
    			
    			<li><a href="/sp/meijoresearch/researcher/cnt/"><img src="https://www.meijo-u.ac.jp/banner/assets/bnr_footer_06.png" alt="ナノサイエンスの先駆者"></a></li>
  				
    			
  				
    			
    			
    			<li><a href="/sp/meijoresearch/researcher/lib/"><img src="https://www.meijo-u.ac.jp/banner/assets/bnr_footer_07.png" alt="リチウムイオン電池の発明者"></a></li>
  				
    			
  				
    			
    			
    			<li><a href="/career/results/"><img src="https://www.meijo-u.ac.jp/banner/assets/bnr_footer_12.png" alt="就職に強い名城大学"></a></li>
  				
    			
  				
    			
    			
    			<li><a href="/sp/sodate/"><img src="https://www.meijo-u.ac.jp/banner/assets/bnr_footer_13.png" alt="育て達人"></a></li>
  				
    			
  				
    			
    			
    			<li><a href="/sp/harbal_medicine/"><img src="https://www.meijo-u.ac.jp/banner/assets/bnr_footer_14.png" alt="漢方随想録"></a></li>
  				
    			
  				
    			
    			
    			<li><a href="http://plat.meijo-u.ac.jp/" target="_blank"><img src="https://www.meijo-u.ac.jp/banner/assets/bnr_footer_04.png" alt="社会連携センターPLAT"></a></li>
  				
    			
  				
    			
    			
    			<li><a href="/globalplaza/"><img src="https://www.meijo-u.ac.jp/banner/assets/bnr_footer_08.png" alt="グローバルプラザ"></a></li>
  				
    			
  				
    			
    			
    			<li><a href="http://up-j.shigaku.go.jp/school/category01/00000000455501000.html" target="_blank"><img src="https://www.meijo-u.ac.jp/banner/assets/bnr_footer_10.png" alt="大学ポートレート"></a></li>
  				
    			
  				
                </ul>
              </div>
            </div>
          </div>
        </div>