<div class="m-list_localnav">
  <div class="l-contents">
    <div class="l-contents-thin">
      <div class="m-list_localnav_inner">
        <div class="m-list_localnav_back"><a href="/academics/">学部・大学院</a></div>
         <h2 class="m-list_localnav_hdg">理工学部</h2>
        <div class="m-list_localnav_list js-action-localnav-target">
          <div>
            <ul>
              <li><a href="/academics/sci_tech/message.html">学部長メッセージ</a></li>
              <li><a href="/academics/sci_tech/mathematics/">数学科</a></li>
              <li><a href="/academics/sci_tech/information/">情報工学科</a></li>
              <li><a href="/academics/sci_tech/electrical">電気電子工学科</a></li>
              <li><a href="/academics/sci_tech/materials/">材料機能工学科</a></li>
              <li><a href="/academics/sci_tech/chemistry/">応用化学科</a></li>
              <li><a href="/academics/sci_tech/mechanical/">機会工学科</a></li>
              <li><a href="/academics/sci_tech/vehicle/">交通機械工学科</a></li>
            </ul>
            <ul>
              <li><a href="/academics/sci_tech/mechatronics/">メカトロニクス工学科</a></li>
              <li><a href="/academics/sci_tech/civil/">社会基盤デザイン工学科</a></li>
              <li><a href="/academics/sci_tech/environmental/">環境創造学科</a></li>
              <li><a href="/academics/sci_tech/architecture/">建築学科</a></li>
              <li><a href="/academics/sci_tech/jabee.html">JABEE</a></li>
              <li><a href="/academics/sci_tech/promote.html">理工学教育推進センター</a></li>
              <li><a href="/academics/sci_tech/report.html">研究報告</a></li>
            </ul>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

<?php include($_SERVER['DOCUMENT_ROOT'] . '/assets/include/pagenav-academics-sci_tech.inc'); ?>