<div class="p-nagoyadome_lfooter">
	<div class="l-contents">
		<p class="p-nagoyadome_lfooter-title">キャンパスから地域へ、キャンパスから世界へ「ナゴヤドーム前キャンパス」</p>
		<div class="m-box_table js-action-boxtable m-box_table-col3">
			<div class="m-box_table_inner">
				<div class="m-box_table_item p-nagoyadome_lfooter-box">
					<a href="/nagoyadome/">
						<img src="/assets/images/nagoyadome/img-nagoyadome01.jpg" alt="">
						<p class="js-match_height"><i class="icon-arrow-right_01"></i>学びの特色</p>
					</a>
				</div>
				<div class="m-box_table_item p-nagoyadome_lfooter-box">
					<a href="/nagoyadome/academics.html">
						<img src="/assets/images/nagoyadome/img-nagoyadome02.jpg" alt="">
						<p class="js-match_height"><i class="icon-arrow-right_01"></i>構成学部・研究科</p>
					</a>
				</div>
				<div class="m-box_table_item p-nagoyadome_lfooter-box">
					<a href="/nagoyadome/community.html">
						<img src="/assets/images/nagoyadome/img-nagoyadome03.jpg" alt="">
						<p class="js-match_height"><i class="icon-arrow-right_01"></i>地域社会や国外の留学生を交えた「学びのコミュニティ」</p>
					</a>
				</div>
			</div>
		</div>
	</div>
</div>