<div class="m-list_localnav">
  <div class="l-contents">
    <div class="l-contents-thin">
      <div class="m-list_localnav_inner">
        <div class="m-list_localnav_back"><a href="/academics/sci_tech/">理工学部</a></div>
         <h2 class="m-list_localnav_hdg">材料機能工学科</h2>
        <div class="m-list_localnav_list js-action-localnav-target">
          <div>
            <ul>
              <li><a href="/academics/sci_tech/materials/message.html">学科長メッセージ</a></li>
              <li><a href="/academics/sci_tech/materials/point.html">学びのポイント</a></li>
              <li><a href="/academics/sci_tech/materials/policy.html">人材養成目的・アドミッションポリシー</a></li>
              <li><a href="/academics/sci_tech/materials/aim.html">学習・教育目標</a></li>
            </ul>
            <ul>
              <li><a href="/academics/sci_tech/materials/pickup.html">科目Pick Up</a></li>
              <li><a href="/academics/sci_tech/materials/research.html">研究室紹介</a></li>
              <li><a href="/academics/sci_tech/materials/license.html">取得できる免許・資格</a></li>
              <li><a href="/academics/sci_tech/materials/educator.html">教員一覧</a></li>
            </ul>
          </div>
        </div>
      </div>
    </div>
  </div>
</div> 

<?php include($_SERVER['DOCUMENT_ROOT'] . '/assets/include/pagenav-academics-sci_tech.inc'); ?>