<div class="m-list_localnav">
  <div class="l-contents">
    <div class="l-contents-thin">
      <div class="m-list_localnav_inner">
        <div class="m-list_localnav_back"><a href="/english/">HOME</a></div>
         <h2 class="m-list_localnav_hdg">About</h2>
        <div class="m-list_localnav_list js-action-localnav-target">
          <div>
            <ul>
              <li><a href="/english/about/mind.html">Philosophy and Founding Spirit</a></li>
              <li><a href="/english/about/data.html">Data on Students and Faculty</a></li>
              <li><a href="/english/about/technology.html">A Source for Leading-Edge Technology</a></li>
              <li><a href="/english/about/accreditation.html">Accreditation</a></li>
              <li><a href="/english/about/greetings.html">Greetings from the President</a></li>
            </ul>
            <ul>
              <li><a href="/english/about/history.html">History</a></li>
              <li><a href="/english/about/finance.html">Financial Information</a></li>
              <li><a href="/english/about/campusmap.html">Campus Information (Access, Campus Map)</a></li>
              <li><a href="/english/about/partner.html">Partner Institutions</a></li>
              <li><a href="/english/about/nagoya.html">The City of Nagoya</a></li>
            </ul>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>