<div class="p-nagoyadome_lheader">
	<div class="l-contents">
		<p class="p-nagoyadome_lheader-title"><img src="/assets/images/nagoyadome/txt-nagoyadome.png" alt="名城大学ナゴヤドーム前キャンパス"></p>
		<ul>
			<li class="p-nagoyadome_lheader_item p-nagoyadome_lheader_item-index"><a href="/nagoyadome/"><span><i class="icon-arrow-right_01"></i>学びの特色</span></a></li>
			<li class="p-nagoyadome_lheader_item p-nagoyadome_lheader_item-academics"><a href="/nagoyadome/academics.html"><span><i class="icon-arrow-right_01"></i>構成学部・研究科</span></a></li>
			<li class="p-nagoyadome_lheader_item p-nagoyadome_lheader_item-community"><a href="/nagoyadome/community.html"><span><i class="icon-arrow-right_01"></i>学びのコミュニティ</span></a></li>
		</ul>
	</div>
</div>