<div class="m-list_localnav">
  <div class="l-contents">
    <div class="l-contents-thin">
      <div class="m-list_localnav_inner">
        <div class="m-list_localnav_back"><a href="/">HOME</a></div>
         <h2 class="m-list_localnav_hdg">学部・大学院</h2>
        <div class="m-list_localnav_list js-action-localnav-target">
          <div>
            <ul>
              <li><a href="/academics/law/">法学部</a></li>
              <li><a href="/academics/business/">経営学部</a></li>
              <li><a href="/academics/economics/">経済学部</a></li>
              <li><a href="/academics/foreign/">外国語学部</a></li>
              <li><a href="/academics/human/">人間学部</a></li>
              <li><a href="/academics/urban/">都市情報学部</a></li>
              <li><a href="/academics/sci_tech/">理工学部</a></li>
              <li><a href="/academics/agriculture/">農学部</a></li>
              <li><a href="/academics/pharmacy/">薬学部</a></li>
            </ul>
            <ul>
              <li><a href="/academics/g_law/">法学研究科</a></li>
              <li><a href="/academics/g_business/">経営学研究科</a></li>
              <li><a href="/academics/g_economics/">経済学研究科</a></li>
              <li><a href="/academics/g_human/">人間学研究科</a></li>
              <li><a href="/academics/g_urban/">都市情報学研究科</a></li>
              <li><a href="/academics/g_sci_tech/">理工学研究科</a></li>
              <li><a href="/academics/g_agriculture/">農学研究科</a></li>
              <li><a href="/academics/g_pharmacy/">薬学研究科</a></li>
              <li><a href="/academics/g_env_human/">総合学術研究科</a></li>
              <li><a href="/academics/law_school/">法務研究科(法科大学院)</a></li>
              <li><a href="/academics/thesis/">博士学位論文</a></li>
              <li><a href="/academics/tc/">教職課程・学芸員課程</a></li>
              <li><a href="/academics/education/">教育への取り組み</a></li>
            </ul>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

<?php include($_SERVER['DOCUMENT_ROOT'] . '/assets/include/pagenav-academics-sci_tech.inc'); ?>