<div class="p-top_meijomag">
			<h2 class="p-top_meijomag_title"><a href="/mag/" target="_blank">MEIJO MAG</a><span>MEIJO UNIVERSITY MAGAZINE</span></h2>
			<div class="p-top_meijomag_main js-action-visible" data-visible="1500">
            
            <div class="p-top_meijomag_main_item p-top_meijomag_main_item-1 p-top_meijomag_item-news p-top_meijomag_main_item-news">
					<a href="/mag/hello-world/detail_20649.html" target="_blank">
					<figure> <span><span class="js-action-imgtobg" data-remove="false"><img src="/assets/images/top/meijomag_46.jpg" alt=""></span></span> <span><span class="js-action-imgtobg"><img src="/assets/images/top/meijomag_46.jpg" alt=""></span></span> </figure>
					<div>
						<div>
							<time><span>2019/04/26</span></time>
							<p><span>HELLO WORLD!</span></p>
							<h3><span>肝が据わったら、<br>自分にも周りの人にも寛容になれました</span></h3>
                		</div>
					</div>
					</a>
			　 </div>

            <!--<div class="p-top_meijomag_main_item p-top_meijomag_main_item-2 p-top_meijomag_item-news p-top_meijomag_main_item-news">
					<a href="https://youtu.be/MtLx2v8fDYE" data-lity>
					<figure> <span><span class="js-action-imgtobg" data-remove="false"><img src="/assets/images/top/meijomag_42.jpg" alt=""></span></span> <span><span class="js-action-imgtobg"><img src="/assets/images/top/meijomag_42.jpg" alt=""></span></span> </figure>
					<div>
						<div>
							<time><span>2019/03/29</span></time>
							<p><span>MOVIE</span></p>
							<h3><span>高める集中力、鋭い目線。<br>名城大学 ライフル射撃部</span></h3>
						</div>
					</div>
					</a>
				</div>-->

            <div class="p-top_meijomag_main_item p-top_meijomag_main_item-2 p-top_meijomag_item-news p-top_meijomag_main_item-news">
					<a href="/mag/feature-people/detail_20998.html" target="_blank">
					<figure> <span><span class="js-action-imgtobg" data-remove="false"><img src="/assets/images/top/meijomag_45.jpg" alt=""></span></span> <span><span class="js-action-imgtobg"><img src="/assets/images/top/meijomag_45.jpg" alt=""></span></span> </figure>
					<div>
						<div>
							<time><span>2019/04/25</span></time>
							<p><span>FEATURE PEOPLE</span></p>
							<h3><span>スイーツ男子、武道で輝く！<br>クッキング部から日本拳法部主将へ</span></h3>
                		</div>
					</div>
					</a>
			　 </div>
			</div>

			<div class="l-contents">
				<div class="l-contents-thin">
					<div class="p-top_meijomag_list js-action-news" data-number="3">
						<ul class="js-action-news-list">
                         <li class="p-top_meijomag_list_item"> <a href="/mag/feature-people/detail_20851.html">
								<figure><img src="/assets/images/top/meijomag_44_2.jpg" alt=""></figure>
								<div>
									<time><span>2019/04/12</span></time>
									<p><span>FEATURE PEOPLE</span></p>
									<h3><span>アラスカ縦断の自転車旅にまもなく出発！<br>大自然が相手の冒険家</span></h3>
								</div>
								</a> </li>
                         <li class="p-top_meijomag_list_item"> <a href="/mag/hello-world/detail_20643.html">
								<figure><img src="/assets/images/top/meijomag_43_2.jpg" alt=""></figure>
								<div>
									<time><span>2019/04/02</span></time>
									<p><span>HELLO WORLD!</span></p>
									<h3><span>将来は海外プロジェクトで活躍できる人になりたい</span></h3>
								</div>
								</a> </li>
                         <li class="p-top_meijomag_list_item"> <a href="/mag/hello-world/detail_20639.html">
								<figure><img src="/assets/images/top/meijomag_42_2.jpg" alt=""></figure>
								<div>
									<time><span>2019/04/01</span></time>
									<p><span>HELLO WORLD!</span></p>
									<h3><span>海外で多様な価値観に触れることで、自由になれました</span></h3>
								</div>
								</a> </li>
                         <li class="p-top_meijomag_list_item"> <a href="/mag/feature-people/detail_20721.html">
								<figure><img src="/assets/images/top/meijomag_40_2.jpg" alt=""></figure>
								<div>
									<time><span>2019/04/01</span></time>
									<p><span>FEATURE PEOPLE</span></p>
									<h3><span>「ハッカソン」で全国優勝！<br>エンジニアの道を邁進する。</span></h3>
								</div>
								</a> </li>
                           <li class="p-top_meijomag_list_item"> <a href="https://youtu.be/MtLx2v8fDYE" target="_blank" data-lity>
								<figure><img src="/assets/images/top/meijomag_41_2.jpg" alt=""></figure>
								<div>
									<time><span>2019/03/29</span></time>
									<p><span>MOVIE</span></p>
									<h3><span>高める集中力、鋭い目線。<br>名城大学 ライフル射撃部</span></h3>
								</div>
								</a> </li>
                         <li class="p-top_meijomag_list_item"> <a href="/mag/hello-world/detail_20632.html">
								<figure><img src="/assets/images/top/meijomag_39_2.jpg" alt=""></figure>
								<div>
									<time><span>2019/03/18</span></time>
									<p><span>HELLO WORLD!</span></p>
									<h3><span>留学は"味見"の一口目。いつか大好物を見つけたい </span></h3>
								</div>
								</a> </li>
                         <li class="p-top_meijomag_list_item"> <a href="/mag/hello-world/detail_20625.html">
								<figure><img src="/assets/images/top/meijomag_38_2.jpg" alt=""></figure>
								<div>
									<time><span>2019/03/18</span></time>
									<p><span>HELLO WORLD!</span></p>
									<h3><span>小さな"できた！"の積み重ねが自信になる</span></h3>
								</div>
								</a> </li>
                         <li class="p-top_meijomag_list_item"> <a href="/mag/feature-people/detail_20718.html">
								<figure><img src="/assets/images/top/meijomag_35_2.jpg" alt=""></figure>
								<div>
									<time><span>2019/03/15</span></time>
									<p><span>FEATURE PEOPLE</span></p>
									<h3><span>目指すは全国ベスト8！<br>チームをまとめる柔道部主将</span></h3>
								</div>
								</a> </li>
                         <li class="p-top_meijomag_list_item"> <a href="/mag/hello-world/detail_20622.html">
								<figure><img src="/assets/images/top/meijomag_37_2.jpg" alt=""></figure>
								<div>
									<time><span>2019/03/14</span></time>
									<p><span>HELLO WORLD!</span></p>
									<h3><span>留学をして、挑戦する楽しさを知りました</span></h3>
								</div>
								</a> </li>
                         <li class="p-top_meijomag_list_item"> <a href="/mag/hello-world/detail_20617.html">
								<figure><img src="/assets/images/top/meijomag_36_2.jpg" alt=""></figure>
								<div>
									<time><span>2019/03/14</span></time>
									<p><span>HELLO WORLD!</span></p>
									<h3><span>海外がますます好きになり、<br>旅行業務取扱管理者の資格を取得！</span></h3>
								</div>
								</a> </li>
                           <li class="p-top_meijomag_list_item"> <a href="https://youtu.be/7ftbDYJ9qnc" target="_blank" data-lity>
								<figure><img src="/assets/images/top/meijomag_34_2.jpg" alt=""></figure>
								<div>
									<time><span>2019/03/13</span></time>
									<p><span>MOVIE</span></p>
									<h3><span>音色の一体感が最高の瞬間に<br>名城大学 管弦楽団</span></h3>
								</div>
								</a> </li>
                         <li class="p-top_meijomag_list_item"> <a href="/mag/hello-world/detail_20242.html">
								<figure><img src="/assets/images/top/meijomag_33_2.jpg" alt=""></figure>
								<div>
									<time><span>2019/03/12</span></time>
									<p><span>HELLO WORLD!</span></p>
									<h3><span>夢を持つことはすばらしい！<br>それに気が付かせてくれたのが留学だった</span></h3>
								</div>
								</a> </li>
                         <li class="p-top_meijomag_list_item"> <a href="/mag/hello-world/detail_20241.html">
								<figure><img src="/assets/images/top/meijomag_32_2.jpg" alt=""></figure>
								<div>
									<time><span>2019/03/08</span></time>
									<p><span>HELLO WORLD!</span></p>
									<h3><span>英語コンプレックスを克服したら、世界につながった！</span></h3>
								</div>
								</a> </li>
                         <li class="p-top_meijomag_list_item"> <a href="/mag/feature-people/detail_20683.html">
								<figure><img src="/assets/images/top/meijomag_29_2.jpg" alt=""></figure>
								<div>
									<time><span>2019/03/07</span></time>
									<p><span>FEATURE PEOPLE</span></p>
									<h3><span>ものづくり好きで燻製機を開発！<br>何でも作る祖父ゆずりのDIY魂</span></h3>
								</div>
								</a> </li>
                         <li class="p-top_meijomag_list_item"> <a href="/mag/hello-world/detail_20203.html">
								<figure><img src="/assets/images/top/meijomag_31_2.jpg" alt=""></figure>
								<div>
									<time><span>2019/03/04</span></time>
									<p><span>HELLO WORLD!</span></p>
									<h3><span>留学の学びは、どれだけ主体性がだせるかが決め手</span></h3>
								</div>
								</a> </li>
                           <li class="p-top_meijomag_list_item"> <a href="https://youtu.be/5gZFc_hHvZQ" target="_blank" data-lity>
								<figure><img src="/assets/images/top/meijomag_28_2.jpg" alt=""></figure>
								<div>
									<time><span>2019/03/01</span></time>
									<p><span>MOVIE</span></p>
									<h3><span>鍛えぬいた心身で上を目指す<br>名城大学 バレーボール部</span></h3>
								</div>
								</a> </li>
                         <li class="p-top_meijomag_list_item"> <a href="/mag/hello-world/detail_20142.html">
								<figure><img src="/assets/images/top/meijomag_30_2.jpg" alt=""></figure>
								<div>
									<time><span>2019/03/01</span></time>
									<p><span>HELLO WORLD!</span></p>
									<h3><span>留学は"消費じゃなくて投資"だ！</span></h3>
								</div>
								</a> </li>
                         <li class="p-top_meijomag_list_item"> <a href="/mag/feature-people/detail_20620.html">
								<figure><img src="/assets/images/top/meijomag_27_2.jpg" alt=""></figure>
								<div>
									<time><span>2019/02/27</span></time>
									<p><span>FEATURE PEOPLE</span></p>
									<h3><span>演奏者の時間と風景を写真に切り取る<br>バンド経験者のライブフォトグラファー</span></h3>
								</div>
								</a> </li>
                         <li class="p-top_meijomag_list_item"> <a href="https://youtu.be/hsBjI5Q5QeY" target="_blank" data-lity>
								<figure><img src="/assets/images/top/meijomag_26_2.jpg" alt=""></figure>
								<div>
									<time><span>2019/02/21</span></time>
									<p><span>MOVIE</span></p>
									<h3><span>見据える先に進むべき道がある。<br>名城大学 弓道部</span></h3>
								</div>
								</a> </li>
                         <li class="p-top_meijomag_list_item"> <a href="/mag/feature-people/detail_20596.html">
								<figure><img src="/assets/images/top/meijomag_25_2.jpg" alt=""></figure>
								<div>
									<time><span>2019/02/15</span></time>
									<p><span>FEATURE PEOPLE</span></p>
									<h3><span>本物みたいな餅つきを体感するVR！？<br>VR界の若きエンターテイナー</span></h3>
								</div>
								</a> </li>
                         <li class="p-top_meijomag_list_item"> <a href="/mag/feature-people/detail_20569.html">
								<figure><img src="/assets/images/top/meijomag_24_2.jpg" alt=""></figure>
								<div>
									<time><span>2019/02/08</span></time>
									<p><span>FEATURE PEOPLE</span></p>
									<h3><span>動物園検定で4年連続満点を達成！<br>動物を愛してやまない物知り博士</span></h3>
								</div>
								</a> </li>
                           <li class="p-top_meijomag_list_item"> <a href="https://youtu.be/cO5UjQ9TtCA" target="_blank" data-lity>
								<figure><img src="/assets/images/top/meijomag_23_2.jpg" alt=""></figure>
								<div>
									<time><span>2019/02/07</span></time>
									<p><span>MOVIE</span></p>
									<h3><span>真剣さの中に楽しさがある。<br>名城大学 将棋部</span></h3>
								</div>
								</a> </li>
                         <li class="p-top_meijomag_list_item"> <a href="/mag/feature-people/detail_20546.html">
								<figure><img src="/assets/images/top/meijomag_22_2.jpg" alt=""></figure>
								<div>
									<time><span>2019/02/01</span></time>
									<p><span>FEATURE PEOPLE</span></p>
									<h3><span>名城大学No.1の台湾マニア！<br>お人好しな台湾コーディネーター</span></h3>
								</div>
								</a> </li>
                          <li class="p-top_meijomag_list_item"> <a href="/mag/feature-people/detail_20464.html">
								<figure><img src="/assets/images/top/meijomag_21_2.jpg" alt=""></figure>
								<div>
									<time><span>2019/01/25</span></time>
									<p><span>FEATURE PEOPLE</span></p>
									<h3><span>誰かの幸せのために働きたい！<br>「象使いの先輩」と呼ばれて</span></h3>
								</div>
								</a> </li>
                          <li class="p-top_meijomag_list_item"> <a href="/mag/feature-people/detail_20385.html">
								<figure><img src="/assets/images/top/meijomag_20_2.jpg" alt=""></figure>
								<div>
									<time><span>2019/01/18</span></time>
									<p><span>FEATURE PEOPLE</span></p>
									<h3><span>日本のゲーム界を変えていく！<br>eスポーツ大学生全国ベスト8</span></h3>
								</div>
								</a> </li>
                          <li class="p-top_meijomag_list_item"> <a href="/mag/feature-people/detail_20382.html">
								<figure><img src="/assets/images/top/meijomag_19_2.jpg" alt=""></figure>
								<div>
									<time><span>2019/01/11</span></time>
									<p><span>FEATURE PEOPLE</span></p>
									<h3><span>日本とインドネシアの架け橋に<br>名城大学のグローバルリーダー</span></h3>
								</div>
								</a> </li>
                          <li class="p-top_meijomag_list_item"> <a href="/mag/diamond/04.html">
								<figure><img src="/assets/images/top/meijomag_18_2.jpg" alt=""></figure>
								<div>
									<time><span>2019/01/07</span></time>
									<p><span>MEIJO DIAMOND</span></p>
									<h3><span>全員が一丸となって果たした栄光の2冠。</span></h3>
								</div>
								</a> </li>
                           <li class="p-top_meijomag_list_item"> <a href="/mag/feature-people/detail_20308.html">
								<figure><img src="/assets/images/top/meijomag_17_2.jpg" alt=""></figure>
								<div>
									<time><span>2018/12/25</span></time>
									<p><span>FEATURE PEOPLE</span></p>
									<h3><span>人を笑顔にする薬剤師を目指して<br>1000人の薬剤師と出会う旅人</span></h3>
								</div>
								</a> </li>
                           <li class="p-top_meijomag_list_item"> <a href="/mag/diamond/03.html">
								<figure><img src="/assets/images/top/meijomag_16_2.jpg" alt=""></figure>
								<div>
									<time><span>2018/12/07</span></time>
									<p><span>MEIJO DIAMOND</span></p>
									<h3><span>未だ続く挑戦の日々</span></h3>
								</div>
								</a> </li>
                           <li class="p-top_meijomag_list_item"> <a href="/mag/feature-people/detail_20184.html">
								<figure><img src="/assets/images/top/meijomag_15_2.jpg" alt=""></figure>
								<div>
									<time><span>2018/12/05</span></time>
									<p><span>FEATURE PEOPLE</span></p>
									<h3><span>人生の“きっかけ”プレゼンター<br>学生団体「Connect」創設者</span></h3>
								</div>
								</a> </li>
                           <li class="p-top_meijomag_list_item"> <a href="/mag/feature-people/detail_20162.html">
								<figure><img src="/assets/images/top/meijomag_14_2.jpg" alt=""></figure>
								<div>
									<time><span>2018/11/29</span></time>
									<p><span>FEATURE PEOPLE</span></p>
									<h3><span>地域の環境保全に大きく貢献！<br>名城大学農学部の“さかなクン”</span></h3>
								</div>
								</a> </li>
						   <li class="p-top_meijomag_list_item"> <a href="/mag/feature-people/detail_20147.html">
								<figure><img src="/assets/images/top/meijomag_13_2.jpg" alt=""></figure>
								<div>
									<time><span>2018/11/22</span></time>
									<p><span>FEATURE PEOPLE</span></p>
									<h3><span>未来のインフルエンサー誕生！<br>日本初（!?）“彫刻刀YouTuber”</span></h3>
								</div>
								</a> </li>
						   <li class="p-top_meijomag_list_item"> <a href="/mag/diamond/02.html">
								<figure><img src="/assets/images/top/meijomag_12_2.jpg" alt=""></figure>
								<div>
									<time><span>2018/10/31</span></time>
									<p><span>MEIJO DIAMOND</span></p>
									<h3><span>目指した「杜の都駅伝」2連覇、その結末は-?</span></h3>
								</div>
								</a> </li>	
                           <li class="p-top_meijomag_list_item"> <a href="https://youtu.be/c8NyzungtBI" target="_blank" data-lity>
								<figure><img src="/assets/images/top/meijomag_11_2.jpg" alt=""></figure>
								<div>
									<time><span>2018/10/31</span></time>
									<p><span>MOVIE</span></p>
									<h3><span>仲間と共に心身を鍛える、<br>名城大学 空手道部</span></h3>
								</div>
								</a> </li>
							<li class="p-top_meijomag_list_item"> <a href="/mag/feature-people/detail_20030.html">
								<figure><img src="/assets/images/top/meijomag_10_2.jpg" alt=""></figure>
								<div>
									<time><span>2018/10/30</span></time>
									<p><span>FEATURE PEOPLE</span></p>
									<h3><span>未来の日本を担う、期待の星<br>内閣府が認めた!? “日本代表”青年</span></h3>
								</div>
								</a> </li>
							<li class="p-top_meijomag_list_item"> <a href="/mag/diamond/01.html">
								<figure><img src="/assets/images/top/meijomag_09_2.jpg" alt=""></figure>
								<div>
									<time><span>2018/10/19</span></time>
									<p><span>MEIJO DIAMOND</span></p>
									<h3><span>10.28 杜の都駅伝連覇への挑戦</span></h3>
								</div>
								</a> </li>
							<li class="p-top_meijomag_list_item"> <a href="https://youtu.be/H_ZvHt43eRQ" data-lity>
								<figure><img src="/assets/images/top/meijomag_08_2.jpg" alt=""></figure>
								<div>
									<time><span>2018/8/29</span></time>
									<p><span>MOVIE</span></p>
									<h3><span>己の精神を磨く、<br>柳生心眼流居合道部</span></h3>
								</div>
								</a> </li>
							<li class="p-top_meijomag_list_item"> <a href="/mag/feature-people/detail_20029.html">
								<figure><img src="/assets/images/top/meijomag_07_2.jpg" alt=""></figure>
								<div>
									<time><span>2018/7/9</span></time>
									<p><span>FEATURE PEOPLE</span></p>
									<h3><span>女子駅伝部のニューホープ<br>
									U20世界陸上競技選手権大会5000m日本代表</span></h3>
								</div>
								</a> </li>
							<li class="p-top_meijomag_list_item"> <a href="https://www.youtube.com/watch?v=S_psy7YSZ_M&feature=youtu.be" data-lity>
								<figure><img src="/assets/images/top/meijomag_07.jpg" alt=""></figure>
								<div>
									<time><span>2018/6/20</span></time>
									<p><span>MOVIE</span></p>
									<h3><span>東海学生ラグビーリーグ制覇を目指す、名城大学ラグビー部</span></h3>
								</div>
								</a> </li>
							<li class="p-top_meijomag_list_item"> <a href="/mag/feature-people/detail_20028.html">
								<figure><img src="/assets/images/top/meijomag_01.jpg" alt=""></figure>
								<div>
									<time><span>2018/5/1</span></time>
									<p><span>FEATURE PEOPLE</span></p>
									<h3><span>世界に挑む！クライミング界の新星</span></h3>
								</div>
								</a> </li>
							<li class="p-top_meijomag_list_item"> <a href="/mag/feature-people/detail_20024.html">
								<figure><img src="/assets/images/top/meijomag_02.jpg" alt=""></figure>
								<div>
									<time><span>2018/5/1</span></time>
									<p><span>FEATURE PEOPLE</span></p>
									<h3><span>歌って踊れるご当地萌えキャラ</span></h3>
								</div>
								</a> </li>
							<li class="p-top_meijomag_list_item"> <a href="/mag/feature-people/detail_20026.html">
								<figure><img src="/assets/images/top/meijomag_03.jpg" alt=""></figure>
								<div>
									<time><span>2018/5/1</span></time>
									<p><span>FEATURE PEOPLE</span></p>
									<h3><span>ラクロス日本代表を、愛知から！</span></h3>
								</div>
								</a> </li>
							<li class="p-top_meijomag_list_item"> <a href="/mag/feature-people/detail_20025.html">
								<figure><img src="/assets/images/top/meijomag_04.jpg" alt=""></figure>
								<div>
									<time><span>2018/5/1</span></time>
									<p><span>FEATURE PEOPLE</span></p>
									<h3><span>成長期が止まらない!? 目指せ2m！</span></h3>
								</div>
								</a> </li>
							<li class="p-top_meijomag_list_item"> <a href="/mag/feature-people/detail_20027.html">
								<figure><img src="/assets/images/top/meijomag_05.jpg" alt=""></figure>
								<div>
									<time><span>2018/5/1</span></time>
									<p><span>FEATURE PEOPLE</span></p>
									<h3><span>頼まれたら断れない？お人好しBOY</span></h3>
								</div>
								</a> </li>
							<li class="p-top_meijomag_list_item"> <a href="/mag/feature-people/detail_20023.html">
								<figure><img src="/assets/images/top/meijomag_06.jpg" alt=""></figure>
								<div>
									<time><span>2018/5/1</span></time>
									<p><span>FEATURE PEOPLE</span></p>
									<h3><span>次世代を牽引するインターンホリック</span></h3>
								</div>
								</a> </li>
						</ul>
						<div class="m-list_news_more js-action-news-more">
							MORE
						</div>
						<div class="m-list_news_link js-action-news-link">
							<a href="/mag/" target="_blank" class="m-btn"><i class="icon-arrow-right_01"></i>一覧へ</a>
						</div>
					</div>
				</div>
			</div>
		</div>