<div class="p-top_mresearch p-top_mresearch-top">
	<div class="l-contents">
		<h2 class="m-hdg_lv2-headline">MEIJO RESEARCH</h2>
		<p class="b-align-center">名城大学の研究成果やプロジェクト実績をご紹介しています</p>
		<ul class="p-top_mresearch_list">
			<li class="p-top_mresearch_item p-top_mresearch_item-new">
				<a href="#">
					<figure><img src="/assets/images/sp/meijoresearch/_dummy/img01.jpg" alt=""></figure>
					<div class="p-top_mresearch_item_box js-match_height">
						<p class="p-top_mresearch_item_box_head">特徴</p>
						<p class="p-top_mresearch_item_box_lead">飛躍する「ゲノム編集」の世界</p>
						<div class="p-top_mresearch_item_box_content">
							<p class="p-top_mresearch_item_box_vol">Vol.<span>03</span></p>
							<p class="p-top_mresearch_item_box_title">AIとこれからの学び</p>
						</div>
					</div>
				</a>
			</li>
			<li class="p-top_mresearch_item">
				<a href="#">
					<figure><img src="/assets/images/sp/meijoresearch/_dummy/img02.jpg" alt=""></figure>
					<div class="p-top_mresearch_item_box js-match_height">
						<p class="p-top_mresearch_item_box_head">特徴</p>
						<div class="p-top_mresearch_item_box_content">
							<p class="p-top_mresearch_item_box_title">AIとこれからの学びAIとこれからの学びAIとこれからの学び</p>
						</div>
					</div>
				</a>
			</li>
			<li class="p-top_mresearch_item">
				<a href="#">
					<figure><img src="/assets/images/sp/meijoresearch/_dummy/img03.jpg" alt=""></figure>
					<div class="p-top_mresearch_item_box js-match_height">
						<p class="p-top_mresearch_item_box_head">特徴</p>
						<div class="p-top_mresearch_item_box_content">
							<p class="p-top_mresearch_item_box_vol">Vol.<span>03</span></p>
							<p class="p-top_mresearch_item_box_title">AIとこれからの学び</p>
						</div>
					</div>
				</a>
			</li>
		</ul>
	</div>
</div>