<meta name="theme-color" content="#ffffff">
<link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon.png">
<link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png">
<link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png">
<link rel="mask-icon" sizes="any" href="/safari-pinned-tab.svg" color="#b7193f">
<link href="https://fonts.googleapis.com/earlyaccess/notosansjapanese.css" rel="stylesheet">
<link href="https://fonts.googleapis.com/css?family=Fira+Sans" rel="stylesheet">
<link href="https://fonts.googleapis.com/css?family=Cinzel" rel="stylesheet">
<link href="https://fonts.googleapis.com/css?family=Montserrat:400,700" rel="stylesheet">
<link href="https://fonts.googleapis.com/css?family=Oswald" rel="stylesheet">
<link href="/assets/css/common.css?v=<?php echo filemtime($_SERVER['DOCUMENT_ROOT'] . '/assets/css/common.css'); ?>" rel="stylesheet">
<link href="/assets/css/print.css" rel="stylesheet" media="print">
<?php include($_SERVER['DOCUMENT_ROOT'] . '/assets/include/ga.inc'); ?>