<aside class="l-pagenav">
<nav class="l-pagenav_wrap js-action-dragscroll js-action-pagenavellipse">
<ul class="l-pagenav_list">
<li class="l-pagenav_list_item"><a href="#"><span>数学</span><p><span>数学科</span></p></a></li>
<li class="l-pagenav_list_item"><a href="#"><span>情報</span><p><span>情報工学科</span></p></a></li>
<li class="l-pagenav_list_item"><a href="#"><span>電気</span><p><span>電気電子工学科</span></p></a></li>
<li class="l-pagenav_list_item"><a href="#"><span>材料</span><p><span>材料機能工学科</span></p></a></li>
<li class="l-pagenav_list_item"><a href="#"><span>応用</span><p><span>応用化学科</span></p></a></li>
<li class="l-pagenav_list_item"><a href="#"><span>機械</span><p><span>機械工学科</span></p></a></li>
<li class="l-pagenav_list_item"><a href="#"><span>交通</span><p><span>交通機械工学科</span></p></a></li>
<li class="l-pagenav_list_item"><a href="#"><span>メカ</span><p><span>メカトロニクス工学科</span></p></a></li>
<li class="l-pagenav_list_item"><a href="#"><span>社会</span><p><span>社会基盤デザイン工学科</span></p></a></li>
<li class="l-pagenav_list_item"><a href="#"><span>環境</span><p><span>環境創造学科</span></p></a></li>
<li class="l-pagenav_list_item"><a href="#"><span>環境</span><p><span>環境創造学科環境創造学科環境創造学科</span></p></a></li>
</ul>
</nav>
</aside>