<aside class="l-pagenav">
<nav class="l-pagenav_wrap js-action-dragscroll js-action-pagenavellipse">
<ul class="l-pagenav_list">
<li class="l-pagenav_list_item l-pagenav_list_item-noellipsis"><a href="#"><i class="icon-news-event_01"></i><p><span>ニュース・イベント</span></p></a></li>
<li class="l-pagenav_list_item"><a href="#"><i class="icon-admissions_01"></i><p><span>入試情報</span></p></a></li>
<li class="l-pagenav_list_item"><a href="#"><i class="icon-academics_01"></i><p><span>学部・大学院</span></p></a></li>
<li class="l-pagenav_list_item"><a href="#"><i class="icon-campuslife_01"></i><p><span>学生生活</span></p></a></li>
<li class="l-pagenav_list_item"><a href="#"><i class="icon-about_01"></i><p><span>大学情報</span></p></a></li>
</ul>
</nav>
</aside>