<div class="l-contents">
	<div class="l-contents-thin">
		<h2 class="m-hdg_lv2">カテゴリ一覧</h2>
		<div class="p-mresearch_category">
			<ul class="p-mresearch_category_list">
				<li class="p-mresearch_category_item">
					<a href="/sp/meijoresearch/feature/">
						<figure><img src="/assets/images/sp/meijoresearch/bg-cat01.jpg" alt=""></figure>
						<span>特集</span>
					</a>
				</li>
				<li class="p-mresearch_category_item">
					<a href="/sp/meijoresearch/researcher/">
						<figure><img src="/assets/images/sp/meijoresearch/bg-cat02.jpg" alt=""></figure>
						<span>世界レベルの研究者たち</span>
					</a>
				</li>
			</ul>
		</div>

		<h2 class="m-hdg_lv2">OTHER RESEARCH</h2>
	</div>
</div>
<div class="p-top_banner">
	<div class="l-contents p-top_banner_inner">
		<div class="l-contents-thin p-top_banner_inner_inner">
			<div class="p-top_banner_slider js-action-bannerslider">
				<ul class="p-top_banner_slider_list clearfix js-action-bannerslider-slider">
					<li>
						<a href="#">
							<img src="/assets/images/top/dammy-banner.png" alt="">
						</a>
					</li>
					<li>
						<a href="#">
							<img src="/assets/images/top/dammy-banner.png" alt="">
						</a>
					</li>
					<li>
						<a href="#">
							<img src="/assets/images/top/dammy-banner.png" alt="">
						</a>
					</li>
					<li>
						<a href="#">
							<img src="/assets/images/top/dammy-banner.png" alt="">
						</a>
					</li>
					<li>
						<a href="#">
							<img src="/assets/images/top/dammy-banner.png" alt="">
						</a>
					</li>
					<li>
						<a href="#">
							<img src="/assets/images/top/dammy-banner.png" alt="">
						</a>
					</li>
				</ul>
			</div>
		</div>
	</div>
</div>