<div class="m-box_feature m-box_feature-mresearch">
	<h2 class="m-hdg_lv2-headline b-mt65-pc">PICK UP</h2>
	<div class="m-box_feature_slider js-action-feature js-action-feature-mresearch">
		<ul class="m-box_feature_slider_list clearfix js-action-feature-slider">
			<li>
				<a href="#">
					<img src="/assets/images/pic-feature01.png" alt="">
					<div class="m-box_feature_slider_list_content p-mresearch_pickup">
						<p class="p-mresearch_pickup_head">特集</p>
						<div class="p-mresearch_pickup_content">
							<p class="p-mresearch_pickup_content_cat">AI人工知能</p>
							<div class="p-mresearch_pickup_content_text">
								<p class="p-mresearch_pickup_content_vol">Vol.<span>03</span></p>
								<p class="p-mresearch_pickup_content_title">AIとこれからの学び(フルバージョン)</p>
							</div>
						</div>
					</div>
				</a>
			</li>
			<li>
				<a href="#">
					<img src="/assets/images/pic-feature02.png" alt="">
					<div class="m-box_feature_slider_list_content p-mresearch_pickup">
						<p class="p-mresearch_pickup_head">特集</p>
						<div class="p-mresearch_pickup_content">
							<div class="p-mresearch_pickup_content_text">
								<p class="p-mresearch_pickup_content_vol">Vol.<span>03</span></p>
								<p class="p-mresearch_pickup_content_title">AIとこれからの学び(カテゴリなし)</p>
							</div>
						</div>
					</div>
				</a>
			</li>
			<li>
				<a href="#">
					<img src="/assets/images/pic-feature03.png" alt="">
					<div class="m-box_feature_slider_list_content p-mresearch_pickup">
						<p class="p-mresearch_pickup_head">特集</p>
						<div class="p-mresearch_pickup_content">
							<p class="p-mresearch_pickup_content_cat">AI人工知能</p>
							<div class="p-mresearch_pickup_content_text">
								<p class="p-mresearch_pickup_content_title">AIとこれからの学び(volなし)</p>
							</div>
						</div>
					</div>
				</a>
			</li>
			<li>
				<a href="#">
					<img src="/assets/images/pic-feature01.png" alt="">
					<div class="m-box_feature_slider_list_content p-mresearch_pickup">
						<p class="p-mresearch_pickup_head">特集</p>
						<div class="p-mresearch_pickup_content">
							<div class="p-mresearch_pickup_content_text">
								<p class="p-mresearch_pickup_content_title">AIとこれからの学び(カテゴリ、volなし)</p>
							</div>
						</div>
					</div>
				</a>
			</li>
			<li>
				<a href="#">
					<img src="/assets/images/pic-feature02.png" alt="">
					<div class="m-box_feature_slider_list_content p-mresearch_pickup">
						<p class="p-mresearch_pickup_head">特集</p>
						<div class="p-mresearch_pickup_content">
							<p class="p-mresearch_pickup_content_cat">AI人工知能</p>
							<div class="p-mresearch_pickup_content_text">
								<p class="p-mresearch_pickup_content_vol">Vol.<span>03</span></p>
								<p class="p-mresearch_pickup_content_title">AIとこれからの学び</p>
							</div>
						</div>
					</div>
				</a>
			</li>
			<li>
				<a href="#">
					<img src="/assets/images/pic-feature03.png" alt="">
					<div class="m-box_feature_slider_list_content p-mresearch_pickup">
						<p class="p-mresearch_pickup_head">特集</p>
						<div class="p-mresearch_pickup_content">
							<p class="p-mresearch_pickup_content_cat">AI人工知能</p>
							<div class="p-mresearch_pickup_content_text">
								<p class="p-mresearch_pickup_content_vol">Vol.<span>03</span></p>
								<p class="p-mresearch_pickup_content_title">AIとこれからの学び</p>
							</div>
						</div>
					</div>
				</a>
			</li>
		</ul>
		<div class="m-box_feature_slider_controll js-action-feature-controll">
			<a class="prev"></a>
			<a class="next"></a>
		</div>
	</div>
</div>