<ul>
                                <li id="lineBtn"></li>
                                <li id="twitterBtn">
                                    <iframe id="twitter-widget-0" scrolling="no" frameborder="0" allowtransparency="true" class="twitter-share-button twitter-share-button-rendered twitter-tweet-button"
                                        title="Twitter Tweet Button" src="https://platform.twitter.com/widgets/tweet_button.eaf4b750247dd4d0c4a27df474e7e934.ja.html#dnt=false&amp;id=twitter-widget-0&amp;lang=ja&amp;original_referer=http%3A%2F%2Fwww.meijo-u.ac.jp%2Fnews%2Fdetail.html%3Fid%3DMIerQT&amp;size=m&amp;text=%E3%80%8CMS-26%E6%8E%A8%E9%80%B2%E6%94%AF%E6%8F%B4%E4%BA%8B%E6%A5%AD%E3%80%8D%E7%B5%8C%E5%96%B6%E5%AD%A6%E9%83%A8%E8%AC%9B%E6%BC%94%E4%BC%9A%E3%82%92%E9%96%8B%E5%82%AC%EF%BD%9C%E5%90%8D%E5%9F%8E%E5%A4%A7%E5%AD%A6&amp;time=1514188851560&amp;type=share&amp;url=http%3A%2F%2Fwww.meijo-u.ac.jp%2Fnews%2Fdetail.html%3Fid%3DMIerQT"
                                        style="position: static; visibility: visible; width: 75px; height: 20px;"></iframe>
                                    <script>!function (d, s, id) { var js, fjs = d.getElementsByTagName(s)[0], p = /^http:/.test(d.location) ? 'http' : 'https'; if (!d.getElementById(id)) { js = d.createElement(s); js.id = id; js.src = p + '://platform.twitter.com/widgets.js'; fjs.parentNode.insertBefore(js, fjs); } }(document, 'script', 'twitter-wjs');</script>
                                </li>
                                <li id="facebookBtn">
                                    <div class="fb-like fb_iframe_widget" data-href="http://www.meijo-u.ac.jp/news/detail.html?id=MIerQT"
                                        data-layout="button_count" data-action="like" data-show-faces="false" data-share="false"
                                        fb-xfbml-state="rendered" fb-iframe-plugin-query="action=like&amp;app_id=209305452567124&amp;container_width=0&amp;href=http%3A%2F%2Fwww.meijo-u.ac.jp%2Fnews%2Fdetail.html%3Fid%3DMIerQT&amp;layout=button_count&amp;locale=ja_JP&amp;sdk=joey&amp;share=false&amp;show_faces=false">
                                        <span style="vertical-align: bottom; width: 83px; height: 20px;">
                                            <iframe name="f38d7ae69a7b6bc" width="1000px" height="1000px" frameborder="0" allowtransparency="true"
                                                allowfullscreen="true" scrolling="no" title="fb:like Facebook Social Plugin"
                                                src="https://www.facebook.com/plugins/like.php?action=like&amp;app_id=209305452567124&amp;channel=http%3A%2F%2Fstaticxx.facebook.com%2Fconnect%2Fxd_arbiter%2Fr%2FlY4eZXm_YWu.js%3Fversion%3D42%23cb%3Df17145975548868%26domain%3Dwww.meijo-u.ac.jp%26origin%3Dhttp%253A%252F%252Fwww.meijo-u.ac.jp%252Ff4a86b85af6bc%26relation%3Dparent.parent&amp;container_width=0&amp;href=http%3A%2F%2Fwww.meijo-u.ac.jp%2Fnews%2Fdetail.html%3Fid%3DMIerQT&amp;layout=button_count&amp;locale=ja_JP&amp;sdk=joey&amp;share=false&amp;show_faces=false"
                                                style="border: none; visibility: visible; width: 83px; height: 20px;" class=""></iframe>
                                        </span>
                                    </div>
                                </li>
                            </ul>