<script src="https://support.ebscohost.com/eit/scripts/ebscohostsearch.js" type="text/javascript"></script>
<div class="m-box_title m-box_title-big m-box_title-startup">

	<div class="m-box_title-startup_search">
		<div class="l-contents">
			<div class="l-contents-thin">
				<h2 class="m-hdg_lv2-headline b-mb5-pc b-mb5-sp meimo-title">meimo</h2>
				<p class="b-align-center meimo-lead b-mb10-sp">meimo(メイモ)は、大学生活に必要な情報が掲載されている学生向けＷＥＢサイトです。</p>
				<div class="m-box_title-startup_search_inner">
					<div class="m-box_title-startup_search_inner_link">
						<ul>
							<li class="m-box_title-startup_search_potal js-match_height"><a href="https://slbsso.meijo-u.ac.jp/opensso/XUI/#login/&goto=https%3A%2F%2Frpportal.meijo-u.ac.jp%3A443%2FPortal%2F" target="_blank"><i class="icon-academics_01"></i>学生ポータルサイト</a></li>
							<li class="m-box_title-startup_search_handbook js-match_height"><a href="https://www.meijo-u.ac.jp/student_staff/guidebook.html"><i class="icon-library_01"></i>学生便覧</a></li>
							<li class="m-box_title-startup_search_calendar js-match_height"><a href="https://www.meijo-u.ac.jp/campus/info/pdf/calendar2019.pdf" target="_blank"><i class="icon-calendar"></i>名城大学カレンダー</a></li>
							<li class="m-box_title-startup_search_mail js-match_height"><a href="https://slbsso.meijo-u.ac.jp/opensso/XUI/#login/&goto=https%3A%2F%2Frpportal.meijo-u.ac.jp%3A443%2FPortal%2F" target="_blank"><i class="icon-device_01"></i>WebClass</a></li>
							<li class="m-box_title-startup_search_lesson js-match_height"><a href="https://gkmsyllabus.meijo-u.ac.jp/camweb/slbssrch.do" target="_blank"><i class="icon-pc_01"></i>授業計画書<br>(シラバス)</a></li>
							<li class="m-box_title-startup_search_procedure js-match_height"><a href="https://www.meijo-u.ac.jp/campus/application/certificate.html"><i class="icon-news-event_01"></i>各種証明書</a></li>
						</ul>
					</div>
					<div class="p-startup-search">
						<form action="/search/" id="cse-search-box" class="m-form_search">
							<input type="hidden" name="cx" value="002002868988497249087:s7bb5bexmyi" />
							<input type="hidden" name="cof" value="FORID:10">
							<input type="hidden" name="ie" value="UTF-8">
							<input type="text" name="q" autocomplete="off" aria-autocomplete="off">
							<button type="submit">
								<i class="icon-search_01"></i>
							</button>
						</form>
					</div>
				</div>
			</div>
		</div>
	</div>
<div class="m-box_title_bg b-bg-main" style="background: url(/assets/images/bg/bg-about.jpg);"></div>
</div>