<div class="p-top_meijomag_list js-action-news js-action-visible" data-number="3" data-visible="1500">
    <div class="l-contents-thin l-contents-thin-edit">
        <ul class="js-action-news-list js-clone-source">
            <li class="p-top_meijomag_list_item"> <a href="/mag/diamond/2020/01.html">
                <figure><img src="/assets/images/top/meijomag_94.jpg" alt=""></figure>
                <div>
                    <div>
                        <time><span>2021/02/04</span></time>
                        <p><span>FEATURE PEOPLE</span></p>
                        <h3><span>企業を巻き込んで環境問題に取り組む！環境団体の設立リーダー</span></h3>
                    </div>
                </div>
                </a> </li>
            <li class="p-top_meijomag_list_item"> <a href="/mag/diamond/2019/04.html">
                <figure><img src="/assets/images/top/meijomag_93.jpg" alt=""></figure>
                <div>
                    <div>
                        <time><span>2021/01/22</span></time>
                        <p><span>FEATURE PEOPLE</span></p>
                        <h3><span>トイレへの探究心が止まらない!夢はトイレのスペシャリスト!?</span></h3>
                    </div>
                </div>
                </a> </li>
            <li class="p-top_meijomag_list_item"> <a href="/mag/diamond/2019/03.html">
                <figure><img src="/assets/images/top/meijomag_92.jpg" alt=""></figure>
                <div>
                    <div>
                        <time><span>2021/02/24</span></time>
                        <p><span>特集：新型コロナウイルス感染症</span></p>
                        <h3><span>変異種検出の新技術</span></h3>
                    </div>
                </div>
                </a> </li>
            <li class="p-top_meijomag_list_item"> <a href="/mag/diamond/2019/02.html">
                <figure><img src="/assets/images/top/meijomag_61.jpg" alt=""></figure>
                <div>
                    <div>
                        <time><span>2021/01/12</span></time>
                        <p><span>MEIJO DAIAMOND</span></p>
                        <h3><span>富士山女子駅伝で3連覇　3年連続2冠を達成</span></h3>
                    </div>
                </div>
                </a> </li>
            <li class="p-top_meijomag_list_item"> <a href="/mag/diamond/2019/01.html">
                <figure><img src="/assets/images/top/meijomag_47.jpg" alt=""></figure>
                <div>
                    <div>
                        <time><span>2021/01/13</span></time>
                        <p><span>FEATURE PEOPLE</span></p>
                        <h3><span>チアスピリットで地域に貢献！笑顔とホスピタリティが武器のスポーツウーマン</span></h3>
                    </div>
                </div>
                </a> </li>
                <li class="p-top_meijomag_list_item"> <a href="/mag/diamond/2018/04.html">
                <figure><img src="/assets/images/top/meijomag_18.jpg" alt=""></figure>
                <div>
                    <div>
                        <time><span>2021/01/06</span></time>
                        <p><span>FEATURE PEOPLE</span></p>
                        <h3><span>夢は日本の社交ダンス界の第一人者！</span></h3>
                    </div>
                </div>
                </a> </li>
            <li class="p-top_meijomag_list_item"> <a href="/mag/diamond/03.html">
                <figure><img src="/assets/images/top/meijomag_17.jpg" alt=""></figure>
                <div>
                    <div>
                        <time><span>2021/02/24</span></time>
                        <p><span>特集：5G</span></p>
                        <h3><span>未来へつながる新世代移動通信５G</span></h3>
                    </div>
                </div>
                </a> </li>
            <li class="p-top_meijomag_list_item"> <a href="/mag/diamond/03.html">
                <figure><img src="/assets/images/top/meijomag_16.jpg" alt=""></figure>
                <div>
                    <div>
                        <time><span>2021/01/13</span></time>
                        <p><span>社会連携PLAT : REPORT</span></p>
                        <h3><span>事例報告「足こぎ車いす“COGY”で、障がい者も健常者...</span></h3>
                    </div>
                </div>
                </a> </li>
           <li class="p-top_meijomag_list_item"> <a href="/mag/feature-people/detail_20184.html">
                <figure><img src="/assets/images/top/meijomag_15_2.jpg" alt=""></figure>
                <div>
                    <div>
                        <time><span>2018/12/05</span></time>
                        <p><span>FEATURE PEOPLE</span></p>
                        <h3><span>人生の“きっかけ”プレゼンター<br>学生団体「Connect」創設者</span></h3>
                    </div>
                </div>
                </a> </li>
           <li class="p-top_meijomag_list_item"> <a href="/mag/feature-people/detail_20162.html">
                <figure><img src="/assets/images/top/meijomag_14_2.jpg" alt=""></figure>
                <div>
                    <div>
                        <time><span>2018/11/29</span></time>
                        <p><span>FEATURE PEOPLE</span></p>
                        <h3><span>地域の環境保全に大きく貢献！<br>名城大学農学部の“さかなクン”</span></h3>
                    </div>
                </div>
                </a> </li>
           <li class="p-top_meijomag_list_item"> <a href="/mag/feature-people/detail_20147.html">
                <figure><img src="/assets/images/top/meijomag_13_2.jpg" alt=""></figure>
                <div>
                    <div>
                        <time><span>2018/11/22</span></time>
                        <p><span>FEATURE PEOPLE</span></p>
                        <h3><span>未来のインフルエンサー誕生！<br>日本初（!?）“彫刻刀YouTuber”</span></h3>
                    </div>
                </div>
                </a> </li>
           <li class="p-top_meijomag_list_item"> <a href="/mag/diamond/02.html">
                <figure><img src="/assets/images/top/meijomag_12_2.jpg" alt=""></figure>
                <div>
                    <div>
                        <time><span>2018/10/31</span></time>
                        <p><span>MEIJO DIAMOND</span></p>
                        <h3><span>目指した「杜の都駅伝」2連覇、その結末は-?</span></h3>
                    </div>
                </div>
                </a> </li>	
           <li class="p-top_meijomag_list_item"> <a href="https://youtu.be/c8NyzungtBI" target="_blank" data-lity>
                <figure><img src="/assets/images/top/meijomag_11_2.jpg" alt=""></figure>
                <div>
                    <div>
                        <time><span>2018/10/31</span></time>
                        <p><span>MOVIE</span></p>
                        <h3><span>仲間と共に心身を鍛える、<br>名城大学空手道部</span></h3>
                    </div>
                </div>
                </a> </li>
            <li class="p-top_meijomag_list_item"> <a href="/mag/feature-people/detail_20030.html">
                <figure><img src="/assets/images/top/meijomag_10_2.jpg" alt=""></figure>
                <div>
                    <div>
                        <time><span>2018/10/30</span></time>
                        <p><span>FEATURE PEOPLE</span></p>
                        <h3><span>未来の日本を担う、期待の星<br>内閣府が認めた!? “日本代表”青年</span></h3>
                    </div>
                </div>
                </a> </li>
            <li class="p-top_meijomag_list_item"> <a href="/mag/diamond/01.html">
                <figure><img src="/assets/images/top/meijomag_09_2.jpg" alt=""></figure>
                <div>
                    <div>
                        <time><span>2018/10/19</span></time>
                        <p><span>MEIJO DIAMOND</span></p>
                        <h3><span>10.28 杜の都駅伝連覇への挑戦</span></h3>
                    </div>
                </div>
                </a> </li>
            <li class="p-top_meijomag_list_item"> <a href="https://youtu.be/H_ZvHt43eRQ" data-lity>
                <figure><img src="/assets/images/top/meijomag_08_2.jpg" alt=""></figure>
                <div>
                    <div>
                        <time><span>2018/8/29</span></time>
                        <p><span>MOVIE</span></p>
                        <h3><span>己の精神を磨く、<br>柳生心眼流居合道部</span></h3>
                    </div>
                </div>
                </a> </li>
            <li class="p-top_meijomag_list_item"> <a href="/mag/feature-people/detail_20029.html">
                <figure><img src="/assets/images/top/meijomag_07_2.jpg" alt=""></figure>
                <div>
                    <div>
                        <time><span>2018/7/9</span></time>
                        <p><span>FEATURE PEOPLE</span></p>
                        <h3><span>女子駅伝部のニューホープ<br>
                        U20世界陸上競技選手権大会5000m日本代表</span></h3>
                    </div>
                </div>
                </a> </li>
            <li class="p-top_meijomag_list_item"> <a href="https://www.youtube.com/watch?v=S_psy7YSZ_M&feature=youtu.be" data-lity>
                <figure><img src="/assets/images/top/meijomag_07.jpg" alt=""></figure>
                <div>
                    <div>
                        <time><span>2018/6/20</span></time>
                        <p><span>MOVIE</span></p>
                        <h3><span>東海学生ラグビーリーグ制覇を目指す、名城大学ラグビー部</span></h3>
                    </div>
                </div>
                </a> </li>
            <li class="p-top_meijomag_list_item"> <a href="/mag/feature-people/detail_20028.html">
                <figure><img src="/assets/images/top/meijomag_01.jpg" alt=""></figure>
                <div>
                    <div>
                        <time><span>2018/5/1</span></time>
                        <p><span>FEATURE PEOPLE</span></p>
                        <h3><span>世界に挑む！クライミング界の新星</span></h3>
                    </div>
                </div>
                </a> </li>
            <li class="p-top_meijomag_list_item"> <a href="/mag/feature-people/detail_20024.html">
                <figure><img src="/assets/images/top/meijomag_02.jpg" alt=""></figure>
                <div>
                    <div>
                        <time><span>2018/5/1</span></time>
                        <p><span>FEATURE PEOPLE</span></p>
                        <h3><span>歌って踊れるご当地萌えキャラ</span></h3>
                    </div>
                </div>
                </a> </li>
            <li class="p-top_meijomag_list_item"> <a href="/mag/feature-people/detail_20026.html">
                <figure><img src="/assets/images/top/meijomag_03.jpg" alt=""></figure>
                <div>
                    <div>
                        <time><span>2018/5/1</span></time>
                        <p><span>FEATURE PEOPLE</span></p>
                        <h3><span>ラクロス日本代表を、愛知から！</span></h3>
                    </div>
                </div>
                </a> </li>
            <li class="p-top_meijomag_list_item"> <a href="/mag/feature-people/detail_20025.html">
                <figure><img src="/assets/images/top/meijomag_04.jpg" alt=""></figure>
                <div>
                    <div>
                        <time><span>2018/5/1</span></time>
                        <p><span>FEATURE PEOPLE</span></p>
                        <h3><span>成長期が止まらない!? 目指せ2m！</span></h3>
                    </div>
                </div>
                </a> </li>
            <li class="p-top_meijomag_list_item"> <a href="/mag/feature-people/detail_20027.html">
                <figure><img src="/assets/images/top/meijomag_05.jpg" alt=""></figure>
                <div>
                    <div>
                        <time><span>2018/5/1</span></time>
                        <p><span>FEATURE PEOPLE</span></p>
                        <h3><span>頼まれたら断れない？お人好しBOY</span></h3>
                    </div>
                </div>
                </a> </li>
            <li class="p-top_meijomag_list_item"> <a href="/mag/feature-people/detail_20023.html">
                <figure><img src="/assets/images/top/meijomag_06.jpg" alt=""></figure>
                <div>
                    <div>
                        <time><span>2018/5/1</span></time>
                        <p><span>FEATURE PEOPLE</span></p>
                        <h3><span>次世代を牽引するインターンホリック</span></h3>
                    </div>
                </div>
                </a> </li>
        </ul>
        <div class="m-list_news_more js-action-news-more">
            MORE
        </div>
        <div class="m-list_news_link js-action-news-link">
            <a href="/mag/" target="_blank" class="m-btn"><i class="icon-arrow-right_01"></i>一覧へ</a>
        </div>
    </div>
</div>
